---
# Dudley Qualifications — Data Cleaning

---
## Objectives

- Inspect the qualifications dataset and its geographical coverage.
- Check for missing values, duplicates and incorrect data types.
- Remove any non-data rows and document cleaning decisions.
- Save and verify a cleaned copy for later analysis.

## Inputs

- Raw dataset: `raw_datasets/dudley_qualifications.csv`
- Source: Office for National Statistics (ONS), Census 2021,
  accessed via Nomis.

  ## Outputs

- Cleaned dataset:
  `cleaned_datasets/dudley_qualifications_cleaned.csv`
- Documented data quality checks and cleaning decisions.

## Additional Comments

- The original raw CSV will remain unchanged.
- Population coverage, units and geographical identifiers
  will be checked before cleaning.
- Missing values and duplicates will be investigated before
  deciding how to handle them.
- Further changes and combining datasets will follow after
  initial cleaning of all five datasets.
- ChatGPT assists with code and documentation; outputs are
  reviewed before findings are recorded.

---

# Change working directory

* We are assuming you will store the notebooks in a subfolder, therefore when running the notebook in the editor, you will need to change the working directory

We need to change the working directory from its current folder to its parent folder
* We access the current directory with os.getcwd()

In [2]:
import os
current_dir = os.getcwd()
current_dir

'c:\\Dudley employment barriers\\jupyter_notebooks'

Move to the parent folder only when the current directory is
jupyter_notebooks. This prevents repeated runs from moving
outside the project folder.

In [3]:
# Move up only when running from the notebooks folder.
if os.path.basename(os.getcwd()) == "jupyter_notebooks":
    os.chdir("..")

print(os.getcwd())

c:\Dudley employment barriers

Confirm the new current directory

In [4]:
current_dir = os.getcwd()
current_dir

'c:\\Dudley employment barriers'

### Working Directory Findings

The working directory is the Dudley employment barriers project
folder. Relative paths can now access raw_datasets and
cleaned_datasets.

---

## 1. Import Libraries

- os: manage the working directory and output folders.
- pandas: load, inspect, clean and save the qualifications dataset.

The os library was also used in the working-directory setup above.

In [5]:
# Import the libraries needed for this cleaning notebook.
import os
import pandas as pd

print("Libraries imported successfully.")

Libraries imported successfully.

### Findings

Both libraries imported successfully. The notebook is ready
to load and inspect the qualifications dataset.

---

## 2. Inspect the Raw Dataset

Read the first ten lines of the qualifications CSV to identify
the title, population coverage, units and column headings.

This will establish whether introductory lines need to be skipped
when loading the full dataset. No changes will be made to the file.

In [6]:
# Set the path to the raw qualifications dataset.
raw_path = "raw_datasets/dudley_qualifications.csv"

# Display the first ten lines with line numbers, including blanks.
with open(raw_path, encoding="utf-8-sig") as file:
    for line_number in range(1, 11):
        line = file.readline()
        if not line:
            break
        print(f"{line_number}: {line.rstrip()}")

1:
2: "TS067 - Highest level of qualification"
3: "ONS Crown Copyright Reserved [from Nomis on 14 October 2026]"
4: "Population :","All usual residents aged 16 years and over"
5: "Units      :","Persons"
6: "Date       :","2021"
7:
8: "2021 super output area - lower layer","mnemonic","Total: All usual residents aged 16 years and over","No qualifications","Level 1 and entry level qualifications","Level 2 qualifications","Apprenticeship","Level 3 qualifications","Level 4 qualifications or above","Other qualifications"
9:
10: "Dudley 001A","E01009763",1637,436,183,289,102,286,296,45

### Findings from the Raw File Inspection

- The dataset is TS067: Highest level of qualification,
  from Census 2021.
- It covers all usual residents aged 16 years and over.
- Values represent counts of persons.
- The geography is 2021 Lower Layer Super Output Areas (LSOAs).
- Column headings appear on line 8, so the first seven lines
  will be skipped when loading the CSV.
- Area names and codes are already separate: the first column
  contains the area name, and mnemonic contains its code.
- There are 10 columns: two area identifiers, a population total
  and seven qualification categories.
- The first visible record is Dudley 001A, code E01009763.

---

### 2.1 Load and Inspect All Records

Load the qualifications CSV, skipping the seven lines before
the column headings.

Display every row and column to inspect the complete dataset
and identify any footer notes or empty records.

In [7]:
# Developed with assistance from ChatGPT.

# Load the CSV using line 8 as the column headings.
df = pd.read_csv(
    raw_path,
    skiprows=7,
    encoding="utf-8-sig"
)

# Display the dimensions and first five rows.
print(f"Rows: {df.shape[0]}, Columns: {df.shape[1]}")
display(df.head())

Rows: 208, Columns: 10

,2021 super output area - lower layer,mnemonic,Total: All usual residents aged 16 years and over,No qualifications,Level 1 and entry level qualifications,Level 2 qualifications,Apprenticeship,Level 3 qualifications,Level 4 qualifications or above,Other qualifications
0,Dudley 001A,E01009763,1637.0,436.0,183.0,289.0,102.0,286.0,296.0,45.0
1,Dudley 001B,E01009764,1266.0,306.0,132.0,187.0,98.0,214.0,279.0,50.0
2,Dudley 001C,E01009767,1265.0,358.0,146.0,220.0,73.0,181.0,238.0,49.0
3,Dudley 001D,E01009769,1428.0,467.0,157.0,244.0,88.0,211.0,221.0,40.0
4,Dudley 001E,E01009770,1215.0,390.0,152.0,188.0,72.0,181.0,198.0,34.0

### Initial inspection findings

- The raw qualifications dataset contains **208 rows and 10 columns**.
- The first five rows show Dudley neighbourhoods, with an **LSOA name** and **unique area code** recorded in separate columns.
- The dataset provides counts of residents aged **16 years and over**, grouped by their highest qualification level.
- Qualification categories range from **no qualifications** to **Level 4 qualifications or above**, alongside apprenticeships and other qualifications.
- Numeric counts currently display as decimals. Missing values and data types will be checked during cleaning.
- These figures are counts rather than percentages. Comparing qualification levels between neighbourhoods will require accounting for differences in population size.

---

## 3. Check missing values and final rows

Inspect missing values and the final five rows to identify any blank
records or source notes included in the CSV.

In [9]:
# Developed with assistance from ChatGPT.

# Check missing values in each column.
print("MISSING VALUES:")
print(df.isna().sum())

# Inspect the final five rows for blank records or source notes.
print("\nFINAL FIVE ROWS:")
display(df.tail())

MISSING VALUES:
2021 super output area - lower layer                 5
mnemonic                                             1
Total: All usual residents aged 16 years and over    5
No qualifications                                    5
Level 1 and entry level qualifications               5
Level 2 qualifications                               5
Apprenticeship                                       5
Level 3 qualifications                               5
Level 4 qualifications or above                      5
Other qualifications                                 5
dtype: int64

FINAL FIVE ROWS:

,2021 super output area - lower layer,mnemonic,Total: All usual residents aged 16 years and over,No qualifications,Level 1 and entry level qualifications,Level 2 qualifications,Apprenticeship,Level 3 qualifications,Level 4 qualifications or above,Other qualifications
203,NaN,In order to protect against disclosure of pers...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
204,NaN,have been swapped between different geographic...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
205,NaN,by small amounts. Small counts at the lowest g...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
206,NaN,affected.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
207,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Findings from the missing-value checks

The missing values are confined to the final five rows. Four contain
source notes about disclosure protection, and the last row is blank.
None represents a neighbourhood, so these are not missing
qualification counts that need to be filled in.

Removing these five rows should leave **203 neighbourhood records**.
The source notes will remain available in the original CSV.

---

## 4. Remove non-data rows

Keep rows containing a valid English LSOA code in the `mnemonic`
column. These codes begin with `E01` followed by six digits.

This will exclude the four source-note rows and the blank row.
Create a separate dataframe called `df_clean` to preserve the
original loaded data, then reset its row index.

Check the number of rows removed and confirm whether any missing
values remain. The original CSV retains the disclosure-control notes.

In [10]:
# Developed with assistance from ChatGPT.

# Check which rows have an English neighbourhood (LSOA) code.
# A valid code starts with E01 and has six more digits.
# Ignore spaces around codes and treat missing codes as invalid.
valid_lsoa = (
    df["mnemonic"]
    .astype("string")
    .str.strip()
    .str.fullmatch(r"E01\d{6}", na=False)
)

# Keep only rows with valid codes in a new table.
# The original table, df, stays unchanged.
df_clean = df.loc[valid_lsoa].copy()

# Restart row numbering at 0, with no gaps.
df_clean.reset_index(drop=True, inplace=True)

# Show how many rows were removed and how many remain.
# Also check whether any empty values remain.
print(f"Original rows: {len(df)}")
print(f"Rows removed: {len(df) - len(df_clean)}")
print(f"Rows remaining: {len(df_clean)}")
print(f"Columns: {df_clean.shape[1]}")
print(f"Remaining missing values: {df_clean.isna().sum().sum()}")

Original rows: 208
Rows removed: 5
Rows remaining: 203
Columns: 10
Remaining missing values: 0

### Findings

The cleaning step removed **5 non-data rows**: four source-note rows
and one blank row. The dataset now contains **203 neighbourhood
records and 10 columns**.

There are **no missing values** in the remaining records, so no
values needed to be filled in. The cleaned data is stored in
`df_clean`, while the original data remains unchanged.

---

## 5. Rename the columns

Replace the long column headings with shorter, descriptive names
that are easier to use in code.

Use `LSOA_Name` and `LSOA_Code` for the neighbourhood identifiers.
Keep the age group in `Total_Aged_16_Plus` so the population covered
by this dataset remains clear.

This step changes column names only; the values remain unchanged.

In [12]:
# Developed with assistance from ChatGPT.

# Match each original column heading to a shorter, clearer name.
# Keep the age group in the total population column name.
column_names = {
    "2021 super output area - lower layer": "LSOA_Name",
    "mnemonic": "LSOA_Code",
    "Total: All usual residents aged 16 years and over": (
        "Total_Aged_16_Plus"
    ),
    "No qualifications": "No_Qualifications",
    "Level 1 and entry level qualifications": "Level_1_And_Entry",
    "Level 2 qualifications": "Level_2",
    "Apprenticeship": "Apprenticeship",
    "Level 3 qualifications": "Level_3",
    "Level 4 qualifications or above": "Level_4_And_Above",
    "Other qualifications": "Other_Qualifications"
}

# Apply the new names without changing the data values.
# Reference: pandas documentation for renaming columns.
# https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rename.html
df_clean = df_clean.rename(columns=column_names)

# Print each column name on a separate line to check the changes.
print("COLUMN NAMES:")
for column in df_clean.columns:
    print(column)

# Check that the number of rows and columns has stayed the same.
print(f"\nRows: {df_clean.shape[0]}, Columns: {df_clean.shape[1]}")

COLUMN NAMES:
LSOA_Name
LSOA_Code
Total_Aged_16_Plus
No_Qualifications
Level_1_And_Entry
Level_2
Apprenticeship
Level_3
Level_4_And_Above
Other_Qualifications

Rows: 203, Columns: 10

### Findings

The column headings now use consistent, readable names with
underscores instead of spaces.

`LSOA_Name` and `LSOA_Code` identify each neighbourhood.
`Total_Aged_16_Plus` makes clear that the qualification counts cover
residents aged 16 and over.

The dataset still contains **203 rows and 10 columns**. Only the
column headings were changed; the data values remain unchanged.

---

## 6. Check for duplicate records

Each neighbourhood should appear once in this dataset.

Check for repeated LSOA codes and completely duplicated rows.
Repeated codes could cause neighbourhoods to be counted more than
once when analysing or joining datasets.

Inspect any duplicates before deciding whether to remove them.

In [13]:
# Developed with assistance from ChatGPT.

# Count rows that repeat an earlier row across every column.
# Reference: pandas documentation for checking duplicates.
# https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.duplicated.html
print(f"Fully duplicated rows: {df_clean.duplicated().sum()}")

# Count neighbourhood codes that appear more than once.
print(
    f"Duplicate LSOA codes: "
    f"{df_clean['LSOA_Code'].duplicated().sum()}"
)

# Mark every row sharing a code, including its first appearance.
duplicate_codes = df_clean["LSOA_Code"].duplicated(keep=False)

# Show up to five affected rows if repeated codes are found.
if duplicate_codes.any():
    print("\nROWS WITH REPEATED LSOA CODES:")
    display(df_clean.loc[duplicate_codes].head())
else:
    print("\nEach LSOA code appears only once.")

Fully duplicated rows: 0
Duplicate LSOA codes: 0

Each LSOA code appears only once.

### Findings

There are **no fully duplicated rows** and **no repeated LSOA codes**.
Each of the **203 neighbourhoods** appears once, so no records need
to be removed.

The LSOA codes are unique within this dataset and can be used to
match neighbourhoods when joining the datasets.

---

## 7. Check data types and population counts

Check how each column is stored before changing any data types.

The qualification columns contain counts of people, so their values
should be numeric, non-negative and whole numbers. Counts may
currently be stored as decimals because the original CSV included
empty cells in its footer rows.

Check for non-numeric entries, negative values and fractional values
before converting the count columns to integers.

In [14]:
# Developed with assistance from ChatGPT.

# Show the current data type of each column.
print("CURRENT DATA TYPES:")
print(df_clean.dtypes)

# Select the count columns, leaving out the area name and code.
count_columns = df_clean.columns.drop(["LSOA_Name", "LSOA_Code"])

# Check whether all count values can be read as numbers.
# Invalid entries become missing values in this temporary table.
# The cleaned dataframe is not changed.
# Reference:
# https://pandas.pydata.org/docs/reference/api/pandas.to_numeric.html
numeric_counts = df_clean[count_columns].apply(
    pd.to_numeric,
    errors="coerce"
)

# Count values that are missing or could not be read as numbers.
print("\nMISSING OR NON-NUMERIC VALUES:")
print(numeric_counts.isna().sum())

# Count values below zero in each column.
print("\nNEGATIVE VALUES:")
print((numeric_counts < 0).sum())

# Whole numbers have no remainder when divided by 1.
# Check only values that are not missing.
print("\nFRACTIONAL VALUES:")
fractional_values = (
    numeric_counts.notna()
    & numeric_counts.mod(1).ne(0)
)
print(fractional_values.sum())

CURRENT DATA TYPES:
LSOA_Name                object
LSOA_Code                object
Total_Aged_16_Plus      float64
No_Qualifications       float64
Level_1_And_Entry       float64
Level_2                 float64
Apprenticeship          float64
Level_3                 float64
Level_4_And_Above       float64
Other_Qualifications    float64
dtype: object

MISSING OR NON-NUMERIC VALUES:
Total_Aged_16_Plus      0
No_Qualifications       0
Level_1_And_Entry       0
Level_2                 0
Apprenticeship          0
Level_3                 0
Level_4_And_Above       0
Other_Qualifications    0
dtype: int64

NEGATIVE VALUES:
Total_Aged_16_Plus      0
No_Qualifications       0
Level_1_And_Entry       0
Level_2                 0
Apprenticeship          0
Level_3                 0
Level_4_And_Above       0
Other_Qualifications    0
dtype: int64

FRACTIONAL VALUES:
Total_Aged_16_Plus      0
No_Qualifications       0
Level_1_And_Entry       0
Level_2                 0
Apprenticeship          0
Level_3                 0
Level_4_And_Above       0
Other_Qualifications    0
dtype: int64

### Findings

The two neighbourhood identifier columns are stored as `object`,
while all eight population-count columns are stored as `float64`
(decimal numbers).

The count columns contain **no missing or non-numeric values,
no negative values and no fractional values**.

All counts are therefore suitable for conversion to integers.
This will display counts as whole numbers without changing their
values.

---

## 8. Convert population counts to integers

The previous checks confirmed that all eight count columns contain
valid, non-negative whole numbers with no missing values.

Convert these columns from `float64` to `int64` so counts display
as whole numbers, such as `1637` instead of `1637.0`.

Leave the neighbourhood names and codes unchanged.

In [15]:
# Developed with assistance from ChatGPT.

# Convert the checked population-count columns to whole numbers.
# Reference: pandas documentation for changing data types.
# https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.astype.html
df_clean[count_columns] = df_clean[count_columns].astype("int64")

# Check that the count columns now use the integer data type.
print("UPDATED DATA TYPES:")
print(df_clean.dtypes)

# Display five rows to check how the counts now appear.
print("\nFIRST FIVE ROWS:")
display(df_clean.head())

UPDATED DATA TYPES:
LSOA_Name               object
LSOA_Code               object
Total_Aged_16_Plus       int64
No_Qualifications        int64
Level_1_And_Entry        int64
Level_2                  int64
Apprenticeship           int64
Level_3                  int64
Level_4_And_Above        int64
Other_Qualifications     int64
dtype: object

FIRST FIVE ROWS:

,LSOA_Name,LSOA_Code,Total_Aged_16_Plus,No_Qualifications,Level_1_And_Entry,Level_2,Apprenticeship,Level_3,Level_4_And_Above,Other_Qualifications
0,Dudley 001A,E01009763,1637,436,183,289,102,286,296,45
1,Dudley 001B,E01009764,1266,306,132,187,98,214,279,50
2,Dudley 001C,E01009767,1265,358,146,220,73,181,238,49
3,Dudley 001D,E01009769,1428,467,157,244,88,211,221,40
4,Dudley 001E,E01009770,1215,390,152,188,72,181,198,34

### Findings

All eight population-count columns now use the `int64` data type,
so counts are stored as whole numbers without decimal places.

The conversion preserved the original count values.
`LSOA_Name` and `LSOA_Code` remain unchanged as `object` columns.

---

## 9. Compare qualification counts with population totals

Add the seven qualification categories for each neighbourhood and
compare their sum with `Total_Aged_16_Plus`.

This checks whether the category counts match the recorded population.
Any differences will be inspected before deciding whether further
action is needed. No values will be changed during this check.

In [17]:
# Developed with assistance from ChatGPT.

# List the seven qualification categories, excluding the total.
qualification_columns = [
    "No_Qualifications",
    "Level_1_And_Entry",
    "Level_2",
    "Apprenticeship",
    "Level_3",
    "Level_4_And_Above",
    "Other_Qualifications"
]

# Add the qualification counts across each row.
# axis=1 means add across columns for each neighbourhood.
# Reference:
# https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sum.html
qualification_sum = df_clean[qualification_columns].sum(axis=1)

# Compare the calculated sum with the recorded population total.
# A difference of zero means the totals match.
# Developed with assistance from ChatGPT.
difference = qualification_sum - df_clean["Total_Aged_16_Plus"]

print(f"Neighbourhoods checked: {len(df_clean)}")
print(f"Matching totals: {(difference == 0).sum()}")
print(f"Non-matching totals: {(difference != 0).sum()}")
print(f"Largest absolute difference: {difference.abs().max()}")

# If any totals differ, display up to five examples.
# Developed with assistance from ChatGPT.
if (difference != 0).any():
    total_checks = df_clean[
        ["LSOA_Name", "LSOA_Code", "Total_Aged_16_Plus"]
    ].copy()
    total_checks["Qualification_Sum"] = qualification_sum
    total_checks["Difference"] = difference

    print("\nEXAMPLES OF NON-MATCHING TOTALS:")
    display(total_checks.loc[difference != 0].head())

Neighbourhoods checked: 203
Matching totals: 203
Non-matching totals: 0
Largest absolute difference: 0

### Findings

The seven qualification categories add up to `Total_Aged_16_Plus`
for **all 203 neighbourhoods**.

There are **no mismatched totals**, and the largest absolute
difference is **0**. No corrections are needed following this check.

---

## 10. Save the cleaned dataset

Save the 203 cleaned neighbourhood records to
`cleaned_datasets/dudley_qualifications_cleaned.csv`.

Exclude the dataframe index from the CSV and keep the original
raw dataset unchanged.

In [18]:
# Developed with assistance from ChatGPT.

from pathlib import Path

# Create a cleaned_datasets folder beside the raw_datasets folder.
cleaned_folder = Path(raw_path).parent.parent / "cleaned_datasets"
cleaned_folder.mkdir(parents=True, exist_ok=True)

# Set the filename for the cleaned qualifications dataset.
cleaned_path = cleaned_folder / "dudley_qualifications_cleaned.csv"

# Save without adding the dataframe's row numbers as a column.
# Use UTF-8 encoding for the CSV.
# Reference: pandas documentation for saving CSV files.
# https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_csv.html
df_clean.to_csv(
    cleaned_path,
    index=False,
    encoding="utf-8-sig"
)

# Confirm the save location and dataset dimensions.
print(f"Saved to: {cleaned_path}")
print(f"Rows: {df_clean.shape[0]}, Columns: {df_clean.shape[1]}")

Saved to: cleaned_datasets\dudley_qualifications_cleaned.csv
Rows: 203, Columns: 10

### Cleaning summary

The cleaned qualifications dataset contains **203 neighbourhoods
and 10 columns**.

- Removed four source-note rows and one blank row.
- Renamed columns for clarity and consistency.
- Confirmed no missing values or duplicate LSOA codes.
- Checked that all population counts are non-negative whole numbers.
- Converted the eight count columns to integers.
- Confirmed qualification categories match the population total
  for every neighbourhood.

Saved as `cleaned_datasets/dudley_qualifications_cleaned.csv`.
The original raw dataset remains unchanged.

---

## Conclusion

The Census 2021 highest qualification dataset has been cleaned and saved as `cleaned_datasets/dudley_qualifications_cleaned.csv`.

The cleaned dataset contains 203 Dudley LSOAs and 10 columns. Non-data rows were removed, columns were renamed, and population counts were converted to integers. Checks found no missing values, duplicate rows or duplicate LSOA codes.

The qualification category counts matched the population total for each area. The original categories were retained, including apprenticeships and other qualifications, without combining them into an assumed ranking.

The dataset is ready for geographic compatibility checks, merging and percentage calculations in notebook 06. Qualification percentages must use the qualification source’s own population total for residents aged 16 and over. The original raw source remains unchanged.

---

## Ethical Considerations — Cleaning Qualification Data

### Purpose and Responsible Use

This notebook prepares Census 2021 qualification data for examining area-level associations between formal qualifications and economic inactivity in Dudley. The data should support investigation of structural barriers without presenting qualifications as a complete measure of a person’s skills, intelligence, experience or employability.

### Reading the Source Data

The code loads the qualification table beneath the introductory metadata. Although those introductory lines are not included as observations, their context must remain documented: the source is Census 2021, the population is usual residents aged 16 years and over, and the units are persons.

This matters because the data does not describe only working-age adults, jobseekers or the current workforce. Source attribution and licensing information should remain accessible in the project documentation.

### Removing Non-Data Rows

Empty rows and footer information are separated from the neighbourhood records so they do not interfere with numeric calculations. Removing these formatting elements should not be confused with excluding residents or neighbourhoods.

A valid area should not be removed simply because it has missing information or an unusual qualification profile. Any exclusion should have an identifiable reason, and explanatory source notes should remain available in the unchanged raw file.

### Renaming Columns

The code replaces lengthy source headings with clearer names for analysis. Renaming must preserve the meaning of each original category, particularly that the table describes residents’ highest qualification level.

These categories should not be relabelled as direct measurements of skills or counts of every qualification a person holds. Clear definitions help prevent simplified column names from producing misleading interpretations.

### Retaining Geographic Identifiers

LSOA codes and names are retained to connect each observation to the correct neighbourhood. Missing or duplicated identifiers could cause incorrect matches or repeated records during later merging.

Checking these identifiers helps prevent one area’s qualification figures from being attributed to another. Compatibility with other geographic boundary versions must still be assessed separately in the merging notebook.

### Converting Counts to Integers

Qualification counts are converted to numeric whole-person values so that totals and later percentages can be calculated consistently. Conversion should preserve the published values and expose unexpected text rather than conceal it.

Missing or unreadable values should not be silently replaced with zero. Zero means that no residents were recorded in a category, which is different from an unavailable value. Confusing the two could distort comparisons between neighbourhoods.

### Checking Missing Values and Duplicates

Missing-value checks help identify incomplete observations. Duplicate-row and duplicate-LSOA checks help prevent a neighbourhood from being counted more than once or receiving unintended weight in later analysis.

Any detected duplicate should be investigated before removal, particularly if records with the same area code contain different values. Passing these checks confirms structural consistency, not that the original Census data is free from uncertainty.

### Comparing Category Counts with Population Totals

The code checks whether the qualification categories sum to the reported population total for each area. This can reveal omitted categories, incorrect column selection or conversion problems.

Agreement is an internal consistency check rather than independent verification of the source. If a discrepancy is found, it should be investigated rather than corrected by changing a category solely to force the totals to match.

### Interpreting No Qualifications

The no-qualifications category must not be described as having no skills. Residents may have practical expertise, employment experience or informal learning that this measure does not capture.

A higher neighbourhood percentage should not be interpreted as evidence of low motivation or inability to work. The measure should not be used to judge individual residents or determine their access to employment support.

### Respecting Different Qualification Routes

Academic qualifications, apprenticeships and other qualifications represent different routes and experiences. Their categories should remain distinct unless there is a clearly documented reason to combine them.

The other-qualifications category should not be treated as equivalent to no qualifications or assigned an assumed level. Preserving the source categories avoids introducing an unsupported hierarchy.

### Using Appropriate Denominators

Later percentages should use the qualification source’s own total for residents aged 16 and over. A total from another Census table should not be substituted simply because it has a similar population description.

The population includes younger residents who may still be studying and older residents who may be retired. Differences in age composition can affect neighbourhood qualification profiles and should be considered when interpreting their relationship with economic inactivity.

### Geographic and Time Coverage

The cleaned data covers 203 Dudley Census 2021 LSOAs. Any exclusions needed for later geographic matching should be recorded in the merging notebook so that the resulting coverage remains transparent.

The figures refer to 2021 and should not be presented as a current assessment of local qualifications. Residents may have moved or gained qualifications since the Census.

### Area-Level Interpretation and Privacy

Neighbourhood statistics should not be used to infer the qualifications of individual residents. An association between no qualifications and economic inactivity does not establish that the same people belong to both groups.

The analysis should remain at the published aggregate level, avoid attempts to identify individuals and use respectful language that does not stigmatise neighbourhoods.

### Saving the Cleaned Dataset

The cleaned file is saved separately so the original raw source remains available for review. Retaining the area identifiers, population totals and category counts supports traceability and later source comparisons.

A successful export does not establish that every transformation was correct. The cleaning steps, checks and limitations should remain documented alongside the saved output.

### Transparency and Accountability

ChatGPT assistance should be acknowledged, and references should explain the methods actually used. Decisions about removing rows, renaming columns and converting values should remain understandable and reviewable.

The cleaned data supports later exploration of associations. It cannot, by itself, establish that qualification deficits cause economic inactivity or justify individual employment decisions.

---