# Cleaning the Dudley Deprivation Dataset

## Purpose
Prepare the deprivation dataset for the Dudley employment barriers project, which explores local factors that may affect people's ability to move into work.

## Objectives
- Inspect the source information, year, structure and geographic coverage.
- Identify the relevant Dudley records and deprivation measures.
- Check missing values, duplicates and data types.
- Check geographic compatibility with the other cleaned datasets.
- Save a validated dataset for later analysis.

## Input
`raw_datasets/dudley_iod.csv`

## Output
`cleaned_datasets/dudley_iod_cleaned.csv`

## Ethical Considerations
Deprivation measures describe areas, not individual circumstances. They should not be used to assume that every resident experiences the same barriers to employment. Source dates and geographic differences will be documented to support responsible interpretation.

## Additional Comments
ChatGPT assisted with planning, code development and documentation.
The original dataset will remain unchanged. This notebook covers cleaning
and validation only; analysis and visualisations will follow separately.

---

# Change working directory

* We are assuming you will store the notebooks in a subfolder, therefore when running the notebook in the editor, you will need to change the working directory

We need to change the working directory from its current folder to its parent folder
* We access the current directory with os.getcwd()

In [1]:
import os
current_dir = os.getcwd()
current_dir

'c:\\Dudley employment barriers\\jupyter_notebooks'

We want to make the parent of the current directory the new current directory
* os.path.dirname() gets the parent directory
* os.chir() defines the new current directory

In [2]:
os.chdir(os.path.dirname(current_dir))
print("You set a new current directory")

You set a new current directory

Confirm the new current directory

In [3]:
current_dir = os.getcwd()
current_dir

'c:\\Dudley employment barriers'

## 1. Inspect the Raw File

Inspect the first ten lines to identify the column headers and any
source information before choosing how to load the dataset.
The original file will remain unchanged.

In [4]:
# Developed with ChatGPT assistance to inspect the raw file structure.
from itertools import islice

raw_path = "raw_datasets/dudley_iod.csv"

# Display the first ten lines with line numbers.
with open(raw_path, "r", encoding="utf-8-sig") as file:
    for line_number, line in enumerate(islice(file, 10), start=1):
        print(f"{line_number}: {line.rstrip()}")

1: LSOA code (2011),LSOA name (2011),Local Authority District code (2019),Local Authority District name (2019),Index of Multiple Deprivation (IMD) Score,Index of Multiple Deprivation (IMD) Rank (where 1 is most deprived),Index of Multiple Deprivation (IMD) Decile (where 1 is most deprived 10% of LSOAs),Income Score (rate),Income Rank (where 1 is most deprived),Income Decile (where 1 is most deprived 10% of LSOAs),Employment Score (rate),Employment Rank (where 1 is most deprived),Employment Decile (where 1 is most deprived 10% of LSOAs),"Education, Skills and Training Score","Education, Skills and Training Rank (where 1 is most deprived)","Education, Skills and Training Decile (where 1 is most deprived 10% of LSOAs)",Health Deprivation and Disability Score,Health Deprivation and Disability Rank (where 1 is most deprived),Health Deprivation and Disability Decile (where 1 is most deprived 10% of LSOAs),Crime Score,Crime Rank (where 1 is most deprived),Crime Decile (where 1 is most deprived 10% of LSOAs),Barriers to Housing and Services Score,Barriers to Housing and Services Rank (where 1 is most deprived),Barriers to Housing and Services Decile (where 1 is most deprived 10% of LSOAs),Living Environment Score,Living Environment Rank (where 1 is most deprived),Living Environment Decile (where 1 is most deprived 10% of LSOAs),Income Deprivation Affecting Children Index (IDACI) Score (rate),Income Deprivation Affecting Children Index (IDACI) Rank (where 1 is most deprived),Income Deprivation Affecting Children Index (IDACI) Decile (where 1 is most deprived 10% of LSOAs),Income Deprivation Affecting Older People (IDAOPI) Score (rate),Income Deprivation Affecting Older People (IDAOPI) Rank (where 1 is most deprived),Income Deprivation Affecting Older People (IDAOPI) Decile (where 1 is most deprived 10% of LSOAs),Children and Young People Sub-domain Score,Children and Young People Sub-domain Rank (where 1 is most deprived),Children and Young People Sub-domain Decile (where 1 is most deprived 10% of LSOAs),Adult Skills Sub-domain Score,Adult Skills Sub-domain Rank (where 1 is most deprived),Adult Skills Sub-domain Decile (where 1 is most deprived 10% of LSOAs),Geographical Barriers Sub-domain Score,Geographical Barriers Sub-domain Rank (where 1 is most deprived),Geographical Barriers Sub-domain Decile (where 1 is most deprived 10% of LSOAs),Wider Barriers Sub-domain Score,Wider Barriers Sub-domain Rank (where 1 is most deprived),Wider Barriers Sub-domain Decile (where 1 is most deprived 10% of LSOAs),Indoors Sub-domain Score,Indoors Sub-domain Rank (where 1 is most deprived),Indoors Sub-domain Decile (where 1 is most deprived 10% of LSOAs),Outdoors Sub-domain Score,Outdoors Sub-domain Rank (where 1 is most deprived),Outdoors Sub-domain Decile (where 1 is most deprived 10% of LSOAs),Total population: mid 2015 (excluding prisoners),Dependent Children aged 0-15: mid 2015 (excluding prisoners),Population aged 16-59: mid 2015 (excluding prisoners),Older population aged 60 and over: mid 2015 (excluding prisoners),Working age population 18-59/64: for use with Employment Deprivation Domain (excluding prisoners)
2: E01000001,City of London 001A,E09000001,City of London,6.208,29199,9,0.007,32831,10,0.01,32742,10,0.024,32842,10,-1.654,32113,10,-2.012,32662,10,29.472,7319,3,31.873,7789,3,0.006,32806,10,0.012,32820,10,-2.107,32777,10,0.032,32843,10,-0.43,22985,7,3.587,3216,1,0.006,16364,5,1.503,1615,1,1296,175,656,465,715
3: E01000002,City of London 001B,E09000001,City of London,5.143,30379,10,0.034,29901,10,0.027,31190,10,0.063,32832,10,-1.115,29705,10,-2.343,32789,10,24.412,11707,4,23.084,13070,4,0.037,29682,10,0.03,31938,10,-1.907,32666,10,0.034,32841,10,-1.06,30223,10,3.231,3894,2,-0.41,22676,7,1.196,2969,1,1156,182,580,394,620
4: E01000003,City of London 001C,E09000001,City of London,19.402,14915,5,0.086,18510,6,0.086,15103,5,5.804,26386,9,-0.102,17600,6,-1.032,29363,9,40.103,2157,1,40.535,4092,2,0.052,27063,9,0.128,16377,5,-0.292,20837,7,0.142,30999,10,-0.691,26719,9,5.173,818,1,-0.054,17318,6,2.207,162,1,1350,146,759,445,804
5: E01000005,City of London 001E,E09000001,City of London,28.652,8678,3,0.211,6029,2,0.136,7833,3,22.26,12370,4,-0.121,17907,6,-1.317,31059,10,39.9,2217,1,28.979,9397,3,0.209,9458,3,0.322,3885,2,0.338,10914,4,0.321,13658,5,-1.167,30865,10,5.361,672,1,-0.604,25218,8,1.769,849,1,1121,229,692,200,683
6: E01000006,Barking and Dagenham 016A,E09000002,Barking and Dagenham,19.837,14486,5,0.117,14023,5,0.059,21692,7,14.798,17511,6,-0.359,21581,7,-0.147,18848,6,45.171,1033,1,26.888,10629,4,0.155,13592,5,0.162,12934,4,-0.366,21932,7,0.325,13244,5,-0.4,22527,7,5.59,520,1,0.11,14745,5,0.969,4368,2,2040,522,1297,221,1285
7: E01000007,Barking and Dagenham 015A,E09000002,Barking and Dagenham,31.576,7256,3,0.207,6261,2,0.107,11487,4,11.385,20536,7,-0.027,16414,5,0.846,4925,2,50.42,274,1,25.995,11162,4,0.253,6750,3,0.371,2514,1,-0.133,18304,6,0.251,21531,7,-0.951,29432,9,6.897,33,1,-0.28,20820,7,1.324,2319,1,2101,572,1424,105,1404
8: E01000008,Barking and Dagenham 015B,E09000002,Barking and Dagenham,37.596,5010,2,0.265,3382,2,0.151,6431,2,25.506,10569,4,0.25,12334,4,0.353,11113,4,45.413,981,1,30.233,8672,3,0.298,4452,2,0.468,893,1,0.129,14007,5,0.384,7918,3,-0.498,24033,8,5.736,443,1,-0.587,25009,8,1.84,674,1,1566,534,961,71,940
9: E01000009,Barking and Dagenham 016B,E09000002,Barking and Dagenham,32.844,6736,3,0.187,7506,3,0.109,11132,4,15.713,16819,6,0.454,9661,3,0.895,4431,2,48.119,554,1,28.601,9611,3,0.194,10487,4,0.383,2238,1,0.101,14445,5,0.277,18554,6,-1.424,31919,10,6.643,92,1,-0.107,18146,6,1.37,2131,1,1775,356,1190,229,1217
10: E01000010,Barking and Dagenham 015C,E09000002,Barking and Dagenham,32.437,6900,3,0.169,8902,3,0.073,17988,6,11.762,20182,7,-0.002,16050,5,1.214,2164,1,50.58,259,1,47.932,2269,1,0.22,8757,3,0.519,531,1,0.022,15696,5,0.228,24261,8,-1.162,30844,10,7.211,6,1,0.931,4411,2,1.271,2600,1,3195,837,2213,145,2234

### Findings
- Column headers appear on the first line.
- The file includes areas outside Dudley, so filtering is required.
- LSOA codes and names use 2011 geography.
- Local authority columns refer to 2019 boundaries.
- Several population columns refer to mid-2015.
- The deprivation release year needs confirmation from the source;
  geographic dates alone do not establish the release year.
- Geographic compatibility with the Census 2021 datasets must be
  checked before merging.
 
 ---

## 2. Load and Preview the Dataset

Load the CSV using the first row as column headers.
Check the number of rows and columns, then preview five records.
Keep the raw dataframe unchanged for reference.

In [5]:
# Developed with ChatGPT assistance to load and inspect the dataset.
import pandas as pd

# Load the raw CSV without skipping any rows.
iod_df = pd.read_csv(raw_path, encoding="utf-8-sig")

# Check the dataset size and preview five records.
print(f"Rows: {iod_df.shape[0]}")
print(f"Columns: {iod_df.shape[1]}")

display(iod_df.head())

Rows: 32844
Columns: 57

,LSOA code (2011),LSOA name (2011),Local Authority District code (2019),Local Authority District name (2019),Index of Multiple Deprivation (IMD) Score,Index of Multiple Deprivation (IMD) Rank (where 1 is most deprived),Index of Multiple Deprivation (IMD) Decile (where 1 is most deprived 10% of LSOAs),Income Score (rate),Income Rank (where 1 is most deprived),Income Decile (where 1 is most deprived 10% of LSOAs),...,Indoors Sub-domain Rank (where 1 is most deprived),Indoors Sub-domain Decile (where 1 is most deprived 10% of LSOAs),Outdoors Sub-domain Score,Outdoors Sub-domain Rank (where 1 is most deprived),Outdoors Sub-domain Decile (where 1 is most deprived 10% of LSOAs),Total population: mid 2015 (excluding prisoners),Dependent Children aged 0-15: mid 2015 (excluding prisoners),Population aged 16-59: mid 2015 (excluding prisoners),Older population aged 60 and over: mid 2015 (excluding prisoners),Working age population 18-59/64: for use with Employment Deprivation Domain (excluding prisoners)
0,E01000001,City of London 001A,E09000001,City of London,6.208,29199,9,0.007,32831,10,...,16364,5,1.503,1615,1,1296,175,656,465,715
1,E01000002,City of London 001B,E09000001,City of London,5.143,30379,10,0.034,29901,10,...,22676,7,1.196,2969,1,1156,182,580,394,620
2,E01000003,City of London 001C,E09000001,City of London,19.402,14915,5,0.086,18510,6,...,17318,6,2.207,162,1,1350,146,759,445,804
3,E01000005,City of London 001E,E09000001,City of London,28.652,8678,3,0.211,6029,2,...,25218,8,1.769,849,1,1121,229,692,200,683
4,E01000006,Barking and Dagenham 016A,E09000002,Barking and Dagenham,19.837,14486,5,0.117,14023,5,...,14745,5,0.969,4368,2,2040,522,1297,221,1285

### Findings
- The dataset loaded successfully with 32,844 rows and 57 columns.
- The five-row preview shows geographic identifiers, deprivation
  measures and population figures in separate columns.
- Records include City of London and Barking and Dagenham,
  confirming that the file is not restricted to Dudley.
- The raw dataset is retained in `iod_df`; no filtering or
  cleaning has been applied.

---

## 3. Select Dudley Records

Select records where the local authority district name is Dudley.
Create a separate copy so the full raw dataframe remains unchanged.
Check the number of selected records and preview five rows.

In [6]:
# Developed with ChatGPT assistance to select Dudley records.

# Filter by the local authority name and retain all columns.
dudley_mask = (
    iod_df["Local Authority District name (2019)"] == "Dudley"
)
iod_clean = iod_df.loc[dudley_mask].copy().reset_index(drop=True)

# Check the selected dataset size and local authority code.
print(f"Dudley rows: {iod_clean.shape[0]}")
print(f"Columns: {iod_clean.shape[1]}")
print(
    "Local authority codes:",
    iod_clean["Local Authority District code (2019)"].unique()
)

display(iod_clean.head())

Dudley rows: 201
Columns: 57
Local authority codes: ['E08000027']

,LSOA code (2011),LSOA name (2011),Local Authority District code (2019),Local Authority District name (2019),Index of Multiple Deprivation (IMD) Score,Index of Multiple Deprivation (IMD) Rank (where 1 is most deprived),Index of Multiple Deprivation (IMD) Decile (where 1 is most deprived 10% of LSOAs),Income Score (rate),Income Rank (where 1 is most deprived),Income Decile (where 1 is most deprived 10% of LSOAs),...,Indoors Sub-domain Rank (where 1 is most deprived),Indoors Sub-domain Decile (where 1 is most deprived 10% of LSOAs),Outdoors Sub-domain Score,Outdoors Sub-domain Rank (where 1 is most deprived),Outdoors Sub-domain Decile (where 1 is most deprived 10% of LSOAs),Total population: mid 2015 (excluding prisoners),Dependent Children aged 0-15: mid 2015 (excluding prisoners),Population aged 16-59: mid 2015 (excluding prisoners),Older population aged 60 and over: mid 2015 (excluding prisoners),Working age population 18-59/64: for use with Employment Deprivation Domain (excluding prisoners)
0,E01009719,Dudley 027A,E08000027,Dudley,19.002,15243,5,0.092,17610,6,...,2099,1,0.124,13252,5,1438,281,807,350,801
1,E01009720,Dudley 028A,E08000027,Dudley,5.745,29752,10,0.038,29138,9,...,28075,9,-0.288,20154,7,1391,244,821,326,839
2,E01009721,Dudley 031A,E08000027,Dudley,21.239,13372,5,0.151,10410,4,...,12971,4,-0.339,21016,7,2030,349,1173,508,1192
3,E01009722,Dudley 027B,E08000027,Dudley,11.606,22637,7,0.061,23560,8,...,8578,3,-0.034,15848,5,1365,215,695,455,718
4,E01009723,Dudley 028B,E08000027,Dudley,5.036,30469,10,0.036,29540,9,...,29616,10,-0.456,22860,7,1237,215,722,300,745

### Findings
- Filtering selected 201 Dudley records and retained all 57 columns.
- All selected records have local authority code `E08000027`.
- The five-row preview shows Dudley LSOA names.
- The selected data is stored separately in `iod_clean`, leaving
  `iod_df` unchanged.
- The row count differs from the 203 rows in the cleaned Census
  datasets. The LSOA codes and boundary differences need checking
  before merging; this does not yet establish missing data.

---

## 4. Check Missing Values and Duplicates

Check the Dudley subset for missing values, duplicate rows and
repeated LSOA codes. Confirm the number of unique codes before
comparing geographic coverage with the Census datasets.

In [7]:
# Developed with ChatGPT assistance to check data completeness.

# Show only columns containing missing values.
missing_values = iod_clean.isna().sum()
print("Columns with missing values:")
print(missing_values[missing_values > 0].to_string())

# Check duplicate records and geographic identifiers.
print("\nDuplicate rows:", iod_clean.duplicated().sum())
print(
    "Duplicate LSOA codes:",
    iod_clean["LSOA code (2011)"].duplicated().sum()
)
print(
    "Unique LSOA codes:",
    iod_clean["LSOA code (2011)"].nunique()
)

Columns with missing values:
Series([], )

Duplicate rows: 0
Duplicate LSOA codes: 0
Unique LSOA codes: 201

### Findings
- No missing values were detected across the 57 columns.
- No duplicate rows or duplicate LSOA codes were found.
- The Dudley subset contains 201 unique LSOA codes.
- No missing-value treatment or duplicate removal is required.

---

# Section 2

Section 2 content

---

NOTE

* You may add as many sections as you want, as long as it supports your project workflow.
* All notebook's cells should be run top-down (you can't create a dynamic wherein a given point you need to go back to a previous cell to execute some task, like go back to a previous cell and refresh a variable content)

---

# Push files to Repo

* In cases where you don't need to push files to Repo, you may replace this section with "Conclusions and Next Steps" and state your conclusions and next steps.

In [ ]:
import os
try:
  # create your folder here
  # os.makedirs(name='')
except Exception as e:
  print(e)