# Cleaning the Dudley Deprivation Dataset

## Purpose
Prepare the deprivation dataset for the Dudley employment barriers project, which explores local factors that may affect people's ability to move into work.

## Objectives
- Inspect the source information, year, structure and geographic coverage.
- Identify the relevant Dudley records and deprivation measures.
- Check missing values, duplicates and data types.
- Check geographic compatibility with the other cleaned datasets.
- Save a validated dataset for later analysis.

## Input
`raw_datasets/dudley_iod.csv`

## Output
`cleaned_datasets/dudley_iod_cleaned.csv`

## Ethical Considerations
Deprivation measures describe areas, not individual circumstances. They should not be used to assume that every resident experiences the same barriers to employment. Source dates and geographic differences will be documented to support responsible interpretation.

## Additional Comments
ChatGPT assisted with planning, code development and documentation.
The original dataset will remain unchanged. This notebook covers cleaning
and validation only; analysis and visualisations will follow separately.

---

# Change working directory

* We are assuming you will store the notebooks in a subfolder, therefore when running the notebook in the editor, you will need to change the working directory

We need to change the working directory from its current folder to its parent folder
* We access the current directory with os.getcwd()

In [1]:
import os
current_dir = os.getcwd()
current_dir

'c:\\Dudley employment barriers\\jupyter_notebooks'

We want to make the parent of the current directory the new current directory
* os.path.dirname() gets the parent directory
* os.chir() defines the new current directory

In [2]:
os.chdir(os.path.dirname(current_dir))
print("You set a new current directory")

You set a new current directory

Confirm the new current directory

In [3]:
current_dir = os.getcwd()
current_dir

'c:\\Dudley employment barriers'

## 1. Inspect the Raw File

Inspect the first ten lines to identify the column headers and any
source information before choosing how to load the dataset.
The original file will remain unchanged.

In [4]:
# Developed with ChatGPT assistance to inspect the raw file structure.
from itertools import islice

raw_path = "raw_datasets/dudley_iod.csv"

# Display the first ten lines with line numbers.
with open(raw_path, "r", encoding="utf-8-sig") as file:
    for line_number, line in enumerate(islice(file, 10), start=1):
        print(f"{line_number}: {line.rstrip()}")

1: LSOA code (2011),LSOA name (2011),Local Authority District code (2019),Local Authority District name (2019),Index of Multiple Deprivation (IMD) Score,Index of Multiple Deprivation (IMD) Rank (where 1 is most deprived),Index of Multiple Deprivation (IMD) Decile (where 1 is most deprived 10% of LSOAs),Income Score (rate),Income Rank (where 1 is most deprived),Income Decile (where 1 is most deprived 10% of LSOAs),Employment Score (rate),Employment Rank (where 1 is most deprived),Employment Decile (where 1 is most deprived 10% of LSOAs),"Education, Skills and Training Score","Education, Skills and Training Rank (where 1 is most deprived)","Education, Skills and Training Decile (where 1 is most deprived 10% of LSOAs)",Health Deprivation and Disability Score,Health Deprivation and Disability Rank (where 1 is most deprived),Health Deprivation and Disability Decile (where 1 is most deprived 10% of LSOAs),Crime Score,Crime Rank (where 1 is most deprived),Crime Decile (where 1 is most deprived 10% of LSOAs),Barriers to Housing and Services Score,Barriers to Housing and Services Rank (where 1 is most deprived),Barriers to Housing and Services Decile (where 1 is most deprived 10% of LSOAs),Living Environment Score,Living Environment Rank (where 1 is most deprived),Living Environment Decile (where 1 is most deprived 10% of LSOAs),Income Deprivation Affecting Children Index (IDACI) Score (rate),Income Deprivation Affecting Children Index (IDACI) Rank (where 1 is most deprived),Income Deprivation Affecting Children Index (IDACI) Decile (where 1 is most deprived 10% of LSOAs),Income Deprivation Affecting Older People (IDAOPI) Score (rate),Income Deprivation Affecting Older People (IDAOPI) Rank (where 1 is most deprived),Income Deprivation Affecting Older People (IDAOPI) Decile (where 1 is most deprived 10% of LSOAs),Children and Young People Sub-domain Score,Children and Young People Sub-domain Rank (where 1 is most deprived),Children and Young People Sub-domain Decile (where 1 is most deprived 10% of LSOAs),Adult Skills Sub-domain Score,Adult Skills Sub-domain Rank (where 1 is most deprived),Adult Skills Sub-domain Decile (where 1 is most deprived 10% of LSOAs),Geographical Barriers Sub-domain Score,Geographical Barriers Sub-domain Rank (where 1 is most deprived),Geographical Barriers Sub-domain Decile (where 1 is most deprived 10% of LSOAs),Wider Barriers Sub-domain Score,Wider Barriers Sub-domain Rank (where 1 is most deprived),Wider Barriers Sub-domain Decile (where 1 is most deprived 10% of LSOAs),Indoors Sub-domain Score,Indoors Sub-domain Rank (where 1 is most deprived),Indoors Sub-domain Decile (where 1 is most deprived 10% of LSOAs),Outdoors Sub-domain Score,Outdoors Sub-domain Rank (where 1 is most deprived),Outdoors Sub-domain Decile (where 1 is most deprived 10% of LSOAs),Total population: mid 2015 (excluding prisoners),Dependent Children aged 0-15: mid 2015 (excluding prisoners),Population aged 16-59: mid 2015 (excluding prisoners),Older population aged 60 and over: mid 2015 (excluding prisoners),Working age population 18-59/64: for use with Employment Deprivation Domain (excluding prisoners)
2: E01000001,City of London 001A,E09000001,City of London,6.208,29199,9,0.007,32831,10,0.01,32742,10,0.024,32842,10,-1.654,32113,10,-2.012,32662,10,29.472,7319,3,31.873,7789,3,0.006,32806,10,0.012,32820,10,-2.107,32777,10,0.032,32843,10,-0.43,22985,7,3.587,3216,1,0.006,16364,5,1.503,1615,1,1296,175,656,465,715
3: E01000002,City of London 001B,E09000001,City of London,5.143,30379,10,0.034,29901,10,0.027,31190,10,0.063,32832,10,-1.115,29705,10,-2.343,32789,10,24.412,11707,4,23.084,13070,4,0.037,29682,10,0.03,31938,10,-1.907,32666,10,0.034,32841,10,-1.06,30223,10,3.231,3894,2,-0.41,22676,7,1.196,2969,1,1156,182,580,394,620
4: E01000003,City of London 001C,E09000001,City of London,19.402,14915,5,0.086,18510,6,0.086,15103,5,5.804,26386,9,-0.102,17600,6,-1.032,29363,9,40.103,2157,1,40.535,4092,2,0.052,27063,9,0.128,16377,5,-0.292,20837,7,0.142,30999,10,-0.691,26719,9,5.173,818,1,-0.054,17318,6,2.207,162,1,1350,146,759,445,804
5: E01000005,City of London 001E,E09000001,City of London,28.652,8678,3,0.211,6029,2,0.136,7833,3,22.26,12370,4,-0.121,17907,6,-1.317,31059,10,39.9,2217,1,28.979,9397,3,0.209,9458,3,0.322,3885,2,0.338,10914,4,0.321,13658,5,-1.167,30865,10,5.361,672,1,-0.604,25218,8,1.769,849,1,1121,229,692,200,683
6: E01000006,Barking and Dagenham 016A,E09000002,Barking and Dagenham,19.837,14486,5,0.117,14023,5,0.059,21692,7,14.798,17511,6,-0.359,21581,7,-0.147,18848,6,45.171,1033,1,26.888,10629,4,0.155,13592,5,0.162,12934,4,-0.366,21932,7,0.325,13244,5,-0.4,22527,7,5.59,520,1,0.11,14745,5,0.969,4368,2,2040,522,1297,221,1285
7: E01000007,Barking and Dagenham 015A,E09000002,Barking and Dagenham,31.576,7256,3,0.207,6261,2,0.107,11487,4,11.385,20536,7,-0.027,16414,5,0.846,4925,2,50.42,274,1,25.995,11162,4,0.253,6750,3,0.371,2514,1,-0.133,18304,6,0.251,21531,7,-0.951,29432,9,6.897,33,1,-0.28,20820,7,1.324,2319,1,2101,572,1424,105,1404
8: E01000008,Barking and Dagenham 015B,E09000002,Barking and Dagenham,37.596,5010,2,0.265,3382,2,0.151,6431,2,25.506,10569,4,0.25,12334,4,0.353,11113,4,45.413,981,1,30.233,8672,3,0.298,4452,2,0.468,893,1,0.129,14007,5,0.384,7918,3,-0.498,24033,8,5.736,443,1,-0.587,25009,8,1.84,674,1,1566,534,961,71,940
9: E01000009,Barking and Dagenham 016B,E09000002,Barking and Dagenham,32.844,6736,3,0.187,7506,3,0.109,11132,4,15.713,16819,6,0.454,9661,3,0.895,4431,2,48.119,554,1,28.601,9611,3,0.194,10487,4,0.383,2238,1,0.101,14445,5,0.277,18554,6,-1.424,31919,10,6.643,92,1,-0.107,18146,6,1.37,2131,1,1775,356,1190,229,1217
10: E01000010,Barking and Dagenham 015C,E09000002,Barking and Dagenham,32.437,6900,3,0.169,8902,3,0.073,17988,6,11.762,20182,7,-0.002,16050,5,1.214,2164,1,50.58,259,1,47.932,2269,1,0.22,8757,3,0.519,531,1,0.022,15696,5,0.228,24261,8,-1.162,30844,10,7.211,6,1,0.931,4411,2,1.271,2600,1,3195,837,2213,145,2234

### Findings
- Column headers appear on the first line.
- The file includes areas outside Dudley, so filtering is required.
- LSOA codes and names use 2011 geography.
- Local authority columns refer to 2019 boundaries.
- Several population columns refer to mid-2015.
- The deprivation release year needs confirmation from the source;
  geographic dates alone do not establish the release year.
- Geographic compatibility with the Census 2021 datasets must be
  checked before merging.
 
 ---

## 2. Load and Preview the Dataset

Load the CSV using the first row as column headers.
Check the number of rows and columns, then preview five records.
Keep the raw dataframe unchanged for reference.

In [5]:
# Developed with ChatGPT assistance to load and inspect the dataset.
import pandas as pd

# Load the raw CSV without skipping any rows.
iod_df = pd.read_csv(raw_path, encoding="utf-8-sig")

# Check the dataset size and preview five records.
print(f"Rows: {iod_df.shape[0]}")
print(f"Columns: {iod_df.shape[1]}")

display(iod_df.head())

Rows: 32844
Columns: 57

,LSOA code (2011),LSOA name (2011),Local Authority District code (2019),Local Authority District name (2019),Index of Multiple Deprivation (IMD) Score,Index of Multiple Deprivation (IMD) Rank (where 1 is most deprived),Index of Multiple Deprivation (IMD) Decile (where 1 is most deprived 10% of LSOAs),Income Score (rate),Income Rank (where 1 is most deprived),Income Decile (where 1 is most deprived 10% of LSOAs),...,Indoors Sub-domain Rank (where 1 is most deprived),Indoors Sub-domain Decile (where 1 is most deprived 10% of LSOAs),Outdoors Sub-domain Score,Outdoors Sub-domain Rank (where 1 is most deprived),Outdoors Sub-domain Decile (where 1 is most deprived 10% of LSOAs),Total population: mid 2015 (excluding prisoners),Dependent Children aged 0-15: mid 2015 (excluding prisoners),Population aged 16-59: mid 2015 (excluding prisoners),Older population aged 60 and over: mid 2015 (excluding prisoners),Working age population 18-59/64: for use with Employment Deprivation Domain (excluding prisoners)
0,E01000001,City of London 001A,E09000001,City of London,6.208,29199,9,0.007,32831,10,...,16364,5,1.503,1615,1,1296,175,656,465,715
1,E01000002,City of London 001B,E09000001,City of London,5.143,30379,10,0.034,29901,10,...,22676,7,1.196,2969,1,1156,182,580,394,620
2,E01000003,City of London 001C,E09000001,City of London,19.402,14915,5,0.086,18510,6,...,17318,6,2.207,162,1,1350,146,759,445,804
3,E01000005,City of London 001E,E09000001,City of London,28.652,8678,3,0.211,6029,2,...,25218,8,1.769,849,1,1121,229,692,200,683
4,E01000006,Barking and Dagenham 016A,E09000002,Barking and Dagenham,19.837,14486,5,0.117,14023,5,...,14745,5,0.969,4368,2,2040,522,1297,221,1285

### Findings
- The dataset loaded successfully with 32,844 rows and 57 columns.
- The five-row preview shows geographic identifiers, deprivation
  measures and population figures in separate columns.
- Records include City of London and Barking and Dagenham,
  confirming that the file is not restricted to Dudley.
- The raw dataset is retained in `iod_df`; no filtering or
  cleaning has been applied.

---

## 3. Select Dudley Records

Select records where the local authority district name is Dudley.
Create a separate copy so the full raw dataframe remains unchanged.
Check the number of selected records and preview five rows.

In [6]:
# Developed with ChatGPT assistance to select Dudley records.

# Filter by the local authority name and retain all columns.
dudley_mask = (
    iod_df["Local Authority District name (2019)"] == "Dudley"
)
iod_clean = iod_df.loc[dudley_mask].copy().reset_index(drop=True)

# Check the selected dataset size and local authority code.
print(f"Dudley rows: {iod_clean.shape[0]}")
print(f"Columns: {iod_clean.shape[1]}")
print(
    "Local authority codes:",
    iod_clean["Local Authority District code (2019)"].unique()
)

display(iod_clean.head())

Dudley rows: 201
Columns: 57
Local authority codes: ['E08000027']

,LSOA code (2011),LSOA name (2011),Local Authority District code (2019),Local Authority District name (2019),Index of Multiple Deprivation (IMD) Score,Index of Multiple Deprivation (IMD) Rank (where 1 is most deprived),Index of Multiple Deprivation (IMD) Decile (where 1 is most deprived 10% of LSOAs),Income Score (rate),Income Rank (where 1 is most deprived),Income Decile (where 1 is most deprived 10% of LSOAs),...,Indoors Sub-domain Rank (where 1 is most deprived),Indoors Sub-domain Decile (where 1 is most deprived 10% of LSOAs),Outdoors Sub-domain Score,Outdoors Sub-domain Rank (where 1 is most deprived),Outdoors Sub-domain Decile (where 1 is most deprived 10% of LSOAs),Total population: mid 2015 (excluding prisoners),Dependent Children aged 0-15: mid 2015 (excluding prisoners),Population aged 16-59: mid 2015 (excluding prisoners),Older population aged 60 and over: mid 2015 (excluding prisoners),Working age population 18-59/64: for use with Employment Deprivation Domain (excluding prisoners)
0,E01009719,Dudley 027A,E08000027,Dudley,19.002,15243,5,0.092,17610,6,...,2099,1,0.124,13252,5,1438,281,807,350,801
1,E01009720,Dudley 028A,E08000027,Dudley,5.745,29752,10,0.038,29138,9,...,28075,9,-0.288,20154,7,1391,244,821,326,839
2,E01009721,Dudley 031A,E08000027,Dudley,21.239,13372,5,0.151,10410,4,...,12971,4,-0.339,21016,7,2030,349,1173,508,1192
3,E01009722,Dudley 027B,E08000027,Dudley,11.606,22637,7,0.061,23560,8,...,8578,3,-0.034,15848,5,1365,215,695,455,718
4,E01009723,Dudley 028B,E08000027,Dudley,5.036,30469,10,0.036,29540,9,...,29616,10,-0.456,22860,7,1237,215,722,300,745

### Findings
- Filtering selected 201 Dudley records and retained all 57 columns.
- All selected records have local authority code `E08000027`.
- The five-row preview shows Dudley LSOA names.
- The selected data is stored separately in `iod_clean`, leaving
  `iod_df` unchanged.
- The row count differs from the 203 rows in the cleaned Census
  datasets. The LSOA codes and boundary differences need checking
  before merging; this does not yet establish missing data.

---

## 4. Check Missing Values and Duplicates

Check the Dudley subset for missing values, duplicate rows and
repeated LSOA codes. Confirm the number of unique codes before
comparing geographic coverage with the Census datasets.

In [7]:
# Developed with ChatGPT assistance to check data completeness.

# Show only columns containing missing values.
missing_values = iod_clean.isna().sum()
print("Columns with missing values:")
print(missing_values[missing_values > 0].to_string())

# Check duplicate records and geographic identifiers.
print("\nDuplicate rows:", iod_clean.duplicated().sum())
print(
    "Duplicate LSOA codes:",
    iod_clean["LSOA code (2011)"].duplicated().sum()
)
print(
    "Unique LSOA codes:",
    iod_clean["LSOA code (2011)"].nunique()
)

Columns with missing values:
Series([], )

Duplicate rows: 0
Duplicate LSOA codes: 0
Unique LSOA codes: 201

### Findings
- No missing values were detected across the 57 columns.
- No duplicate rows or duplicate LSOA codes were found.
- The Dudley subset contains 201 unique LSOA codes.
- No missing-value treatment or duplicate removal is required.

---

## 5. Compare LSOA Codes with the Census Dataset

Compare the deprivation dataset's 2011 LSOA codes with the codes
in the cleaned economic activity dataset.

Identify shared codes and codes appearing in only one dataset.
This is an initial compatibility check; it does not by itself
confirm that geographic boundaries are identical.

In [8]:
# Developed with ChatGPT assistance to compare geographic coverage.

# Load the cleaned Census economic activity dataset.
economic_df = pd.read_csv(
    "cleaned_datasets/dudley_economic_activity_cleaned.csv"
)

# Compare unique LSOA codes from the two datasets.
iod_codes = set(iod_clean["LSOA code (2011)"])
census_codes = set(economic_df["LSOA_Code"])

print("Shared LSOA codes:", len(iod_codes & census_codes))
print("Codes only in deprivation data:", len(iod_codes - census_codes))
print("Codes only in Census data:", len(census_codes - iod_codes))

# Display the areas requiring further investigation.
print("\nAreas only in deprivation data:")
display(
    iod_clean.loc[
        iod_clean["LSOA code (2011)"].isin(iod_codes - census_codes),
        ["LSOA code (2011)", "LSOA name (2011)"]
    ]
)

print("\nAreas only in Census data:")
display(
    economic_df.loc[
        economic_df["LSOA_Code"].isin(census_codes - iod_codes),
        ["LSOA_Code", "LSOA_Name"]
    ]
)

Shared LSOA codes: 199
Codes only in deprivation data: 2
Codes only in Census data: 4

Areas only in deprivation data:

    LSOA code (2011) LSOA name (2011)
160        E01009881      Dudley 011C
200        E01033187      Dudley 006G

Areas only in Census data:

    LSOA_Code    LSOA_Name
29  E01034306  Dudley 006H
30  E01034307  Dudley 006I
53  E01034308  Dudley 011E
54  E01034309  Dudley 011F

### Findings
- The datasets share 199 LSOA codes.
- Two codes appear only in the deprivation dataset:
  - `E01009881` — Dudley 011C.
  - `E01033187` — Dudley 006G.
- Four codes appear only in the Census dataset:
  - `E01034306` — Dudley 006H.
  - `E01034307` — Dudley 006I.
  - `E01034308` — Dudley 011E.
  - `E01034309` — Dudley 011F.
- A direct inner merge would retain only the 199 shared codes,
  excluding four Census areas.
- The area names suggest possible boundary splits, but an official
  lookup is needed to confirm the relationships.
- Geographic differences require investigation before deciding
  how to combine the datasets. No records have been removed.

---

## 6. Inspect Column Data Types

Inspect the data type of every column before selecting or renaming
variables. Geographic identifiers should remain text, while
deprivation measures and population figures should be numeric.

Scores, ranks, deciles and population counts represent different
types of measurements and will require different validation rules.

In [9]:
# Developed with ChatGPT assistance to inspect column data types.

# Display every column and its current data type.
print(iod_clean.dtypes.to_string())

# Identify columns currently stored as text.
text_columns = iod_clean.select_dtypes(include="object").columns

print("\nText columns:")
for column in text_columns:
    print(column)

LSOA code (2011)                                                                                       object
LSOA name (2011)                                                                                       object
Local Authority District code (2019)                                                                   object
Local Authority District name (2019)                                                                   object
Index of Multiple Deprivation (IMD) Score                                                             float64
Index of Multiple Deprivation (IMD) Rank (where 1 is most deprived)                                     int64
Index of Multiple Deprivation (IMD) Decile (where 1 is most deprived 10% of LSOAs)                      int64
Income Score (rate)                                                                                   float64
Income Rank (where 1 is most deprived)                                                                  int64
Income Decile (where 1 is most deprived 10% of LSOAs)                                                   int64
Employment Score (rate)                                                                               float64
Employment Rank (where 1 is most deprived)                                                              int64
Employment Decile (where 1 is most deprived 10% of LSOAs)                                               int64
Education, Skills and Training Score                                                                  float64
Education, Skills and Training Rank (where 1 is most deprived)                                          int64
Education, Skills and Training Decile (where 1 is most deprived 10% of LSOAs)                           int64
Health Deprivation and Disability Score                                                               float64
Health Deprivation and Disability Rank (where 1 is most deprived)                                       int64
Health Deprivation and Disability Decile (where 1 is most deprived 10% of LSOAs)                        int64
Crime Score                                                                                           float64
Crime Rank (where 1 is most deprived)                                                                   int64
Crime Decile (where 1 is most deprived 10% of LSOAs)                                                    int64
Barriers to Housing and Services Score                                                                float64
Barriers to Housing and Services Rank (where 1 is most deprived)                                        int64
Barriers to Housing and Services Decile (where 1 is most deprived 10% of LSOAs)                         int64
Living Environment Score                                                                              float64
Living Environment Rank (where 1 is most deprived)                                                      int64
Living Environment Decile (where 1 is most deprived 10% of LSOAs)                                       int64
Income Deprivation Affecting Children Index (IDACI) Score (rate)                                      float64
Income Deprivation Affecting Children Index (IDACI) Rank (where 1 is most deprived)                     int64
Income Deprivation Affecting Children Index (IDACI) Decile (where 1 is most deprived 10% of LSOAs)      int64
Income Deprivation Affecting Older People (IDAOPI) Score (rate)                                       float64
Income Deprivation Affecting Older People (IDAOPI) Rank (where 1 is most deprived)                      int64
Income Deprivation Affecting Older People (IDAOPI) Decile (where 1 is most deprived 10% of LSOAs)       int64
Children and Young People Sub-domain Score                                                            float64
Children and Young People Sub-domain Rank (where 1 is most deprived)                                    int64
Children and Young People Sub-domain Decile (where 1 is most deprived 10% of LSOAs)                     int64
Adult Skills Sub-domain Score                                                                         float64
Adult Skills Sub-domain Rank (where 1 is most deprived)                                                 int64
Adult Skills Sub-domain Decile (where 1 is most deprived 10% of LSOAs)                                  int64
Geographical Barriers Sub-domain Score                                                                float64
Geographical Barriers Sub-domain Rank (where 1 is most deprived)                                        int64
Geographical Barriers Sub-domain Decile (where 1 is most deprived 10% of LSOAs)                         int64
Wider Barriers Sub-domain Score                                                                       float64
Wider Barriers Sub-domain Rank (where 1 is most deprived)                                               int64
Wider Barriers Sub-domain Decile (where 1 is most deprived 10% of LSOAs)                                int64
Indoors Sub-domain Score                                                                              float64
Indoors Sub-domain Rank (where 1 is most deprived)                                                      int64
Indoors Sub-domain Decile (where 1 is most deprived 10% of LSOAs)                                       int64
Outdoors Sub-domain Score                                                                             float64
Outdoors Sub-domain Rank (where 1 is most deprived)                                                     int64
Outdoors Sub-domain Decile (where 1 is most deprived 10% of LSOAs)                                      int64
Total population: mid 2015 (excluding prisoners)                                                        int64
Dependent Children aged 0-15: mid 2015 (excluding prisoners)                                            int64
Population aged 16-59: mid 2015 (excluding prisoners)                                                   int64
Older population aged 60 and over: mid 2015 (excluding prisoners)                                       int64
Working age population 18-59/64: for use with Employment Deprivation Domain (excluding prisoners)       int64

Text columns:
LSOA code (2011)
LSOA name (2011)
Local Authority District code (2019)
Local Authority District name (2019)

### Findings
- The four geographic code and name columns are stored as text
  (`object`), preserving their identifiers.
- Deprivation scores and rates are stored as decimal numbers
  (`float64`).
- Ranks, deciles and population counts are stored as integers
  (`int64`).
- No numeric measure columns were loaded as text, so no data type
  conversions are needed at this stage.
- Numeric ranges still need validation; correct data types alone
  do not confirm that the values are valid.

---

## 7. Validate Ranks and Deciles

Check that ranks fall between 1 and the number of records in the
full source dataset (32,844), and that deciles fall between 1 and 10.

Use the full dataset size because these rankings compare areas
nationally, rather than only within Dudley. Retain the original
rank and decile values.

In [10]:
# Developed with ChatGPT assistance to validate ranks and deciles.

# Identify rank and decile columns using their existing names.
rank_columns = [
    column for column in iod_clean.columns if " Rank " in column
]
decile_columns = [
    column for column in iod_clean.columns if " Decile " in column
]

# Count values outside the expected ranges in each column.
invalid_ranks = iod_clean[rank_columns].apply(
    lambda column: (~column.between(1, len(iod_df))).sum()
)
invalid_deciles = iod_clean[decile_columns].apply(
    lambda column: (~column.between(1, 10)).sum()
)

print(f"Rank columns checked: {len(rank_columns)}")
print("Out-of-range ranks:")
print(invalid_ranks.to_string())

print(f"\nDecile columns checked: {len(decile_columns)}")
print("Out-of-range deciles:")
print(invalid_deciles.to_string())

Rank columns checked: 16
Out-of-range ranks:
Index of Multiple Deprivation (IMD) Rank (where 1 is most deprived)                    0
Income Rank (where 1 is most deprived)                                                 0
Employment Rank (where 1 is most deprived)                                             0
Education, Skills and Training Rank (where 1 is most deprived)                         0
Health Deprivation and Disability Rank (where 1 is most deprived)                      0
Crime Rank (where 1 is most deprived)                                                  0
Barriers to Housing and Services Rank (where 1 is most deprived)                       0
Living Environment Rank (where 1 is most deprived)                                     0
Income Deprivation Affecting Children Index (IDACI) Rank (where 1 is most deprived)    0
Income Deprivation Affecting Older People (IDAOPI) Rank (where 1 is most deprived)     0
Children and Young People Sub-domain Rank (where 1 is most deprived)                   0
Adult Skills Sub-domain Rank (where 1 is most deprived)                                0
Geographical Barriers Sub-domain Rank (where 1 is most deprived)                       0
Wider Barriers Sub-domain Rank (where 1 is most deprived)                              0
Indoors Sub-domain Rank (where 1 is most deprived)                                     0
Outdoors Sub-domain Rank (where 1 is most deprived)                                    0

Decile columns checked: 16
Out-of-range deciles:
Index of Multiple Deprivation (IMD) Decile (where 1 is most deprived 10% of LSOAs)                    0
Income Decile (where 1 is most deprived 10% of LSOAs)                                                 0
Employment Decile (where 1 is most deprived 10% of LSOAs)                                             0
Education, Skills and Training Decile (where 1 is most deprived 10% of LSOAs)                         0
Health Deprivation and Disability Decile (where 1 is most deprived 10% of LSOAs)                      0
Crime Decile (where 1 is most deprived 10% of LSOAs)                                                  0
Barriers to Housing and Services Decile (where 1 is most deprived 10% of LSOAs)                       0
Living Environment Decile (where 1 is most deprived 10% of LSOAs)                                     0
Income Deprivation Affecting Children Index (IDACI) Decile (where 1 is most deprived 10% of LSOAs)    0
Income Deprivation Affecting Older People (IDAOPI) Decile (where 1 is most deprived 10% of LSOAs)     0
Children and Young People Sub-domain Decile (where 1 is most deprived 10% of LSOAs)                   0
Adult Skills Sub-domain Decile (where 1 is most deprived 10% of LSOAs)                                0
Geographical Barriers Sub-domain Decile (where 1 is most deprived 10% of LSOAs)                       0
Wider Barriers Sub-domain Decile (where 1 is most deprived 10% of LSOAs)                              0
Indoors Sub-domain Decile (where 1 is most deprived 10% of LSOAs)                                     0
Outdoors Sub-domain Decile (where 1 is most deprived 10% of LSOAs)                                    0

### Findings
- All 16 rank columns were checked across the 201 Dudley records.
- No ranks fall outside the expected range of 1 to 32,844.
- All 16 decile columns were checked.
- No deciles fall outside the expected range of 1 to 10.
- No corrections were required. Original ranks and deciles have
  been retained without recalculating them for Dudley.

---

## 8. Validate Explicit Rate Columns

Check that columns labelled `Score (rate)` contain values between
0 and 1, representing proportions.

Apply this check only to explicitly labelled rates. Other deprivation
scores use different scales and must not be treated as proportions.
Keep the original values unchanged.

In [11]:
# Developed with ChatGPT assistance to validate explicit rate columns.

# Select only columns explicitly labelled as rates.
rate_columns = [
    column for column in iod_clean.columns
    if "Score (rate)" in column
]

# Summarise the range and count invalid values for each rate.
rate_checks = pd.DataFrame({
    "Minimum": iod_clean[rate_columns].min(),
    "Maximum": iod_clean[rate_columns].max(),
    "Outside_0_to_1": iod_clean[rate_columns].apply(
        lambda column: (~column.between(0, 1)).sum()
    )
})

print(f"Rate columns checked: {len(rate_columns)}")
display(rate_checks)

Rate columns checked: 4

,Minimum,Maximum,Outside_0_to_1
Income Score (rate),0.020,0.408,0
Employment Score (rate),0.021,0.302,0
Income Deprivation Affecting Children Index (IDACI) Score (rate),0.014,0.573,0
Income Deprivation Affecting Older People (IDAOPI) Score (rate),0.027,0.451,0

### Findings
- All four explicitly labelled rate columns contain values between
  0 and 1, with no out-of-range values.
- Observed ranges are:
  - Income: 0.020–0.408.
  - Employment: 0.021–0.302.
  - Income Deprivation Affecting Children (IDACI): 0.014–0.573.
  - Income Deprivation Affecting Older People (IDAOPI): 0.027–0.451.
- No corrections were required. Rates remain in their original
  proportion format.

---

## 9. Validate Population Counts

Check the five population columns for negative or fractional values.
Population counts should be non-negative whole numbers.

These columns describe different population groups. Do not add them
all together, because the working-age population overlaps other groups.

In [12]:
# Developed with ChatGPT assistance to validate population counts.

# Identify population columns from their existing names.
population_columns = [
    column for column in iod_clean.columns
    if "population" in column.lower()
    or column.startswith("Dependent Children")
]

# Check each column without changing the original values.
population_checks = pd.DataFrame({
    "Minimum": iod_clean[population_columns].min(),
    "Maximum": iod_clean[population_columns].max(),
    "Negative_values": (
        iod_clean[population_columns] < 0
    ).sum(),
    "Fractional_values": (
        iod_clean[population_columns] % 1 != 0
    ).sum()
})

print(f"Population columns checked: {len(population_columns)}")
display(population_checks)

Population columns checked: 5

,Minimum,Maximum,Negative_values,Fractional_values
Total population: mid 2015 (excluding prisoners),1139,3122,0,0
Dependent Children aged 0-15: mid 2015 (excluding prisoners),152,1038,0,0
Population aged 16-59: mid 2015 (excluding prisoners),526,1700,0,0
Older population aged 60 and over: mid 2015 (excluding prisoners),176,653,0,0
Working age population 18-59/64: for use with Employment Deprivation Domain (excluding prisoners),539,1673,0,0

### Findings
- All five population columns were checked across the Dudley subset.
- No negative or fractional values were found.
- Total population values range from 1,139 to 3,122 per area.
- All five columns already use the integer data type (`int64`),
  so no conversion or rounding is required.
- The original population counts have been retained unchanged.

---

## 10. Check Population Totals

Check whether the three non-overlapping age groups—0–15, 16–59
and 60 and over—sum to the stated mid-2015 total population.

Exclude the employment-domain working-age population from this sum
because it overlaps these age groups. Report any differences without
changing the original counts.

In [13]:
# Developed with ChatGPT assistance to check population totals.

# Select the three age groups covering the total population.
age_columns = [
    "Dependent Children aged 0-15: mid 2015 (excluding prisoners)",
    "Population aged 16-59: mid 2015 (excluding prisoners)",
    "Older population aged 60 and over: mid 2015 (excluding prisoners)"
]
total_column = "Total population: mid 2015 (excluding prisoners)"

# Compare the age-group sum with the stated total.
age_total = iod_clean[age_columns].sum(axis=1)
population_difference = age_total - iod_clean[total_column]
population_mismatch = population_difference.ne(0)

print(
    "Rows where age groups do not match the total:",
    population_mismatch.sum()
)

# Preview any mismatches, limiting the output to five rows.
display(
    iod_clean.loc[
        population_mismatch,
        ["LSOA code (2011)", total_column] + age_columns
    ].head()
)

Rows where age groups do not match the total: 0

Empty DataFrame
Columns: [LSOA code (2011), Total population: mid 2015 (excluding prisoners), Dependent Children aged 0-15: mid 2015 (excluding prisoners), Population aged 16-59: mid 2015 (excluding prisoners), Older population aged 60 and over: mid 2015 (excluding prisoners)]
Index: []

### Findings
- The three age groups sum exactly to the stated mid-2015 total
  population for all 201 Dudley records.
- No mismatches were found, so the displayed exceptions table is empty.
- The overlapping employment-domain working-age population was
  excluded from this calculation.
- No corrections were required.

---

# Section 2

Section 2 content

---

NOTE

* You may add as many sections as you want, as long as it supports your project workflow.
* All notebook's cells should be run top-down (you can't create a dynamic wherein a given point you need to go back to a previous cell to execute some task, like go back to a previous cell and refresh a variable content)

---

# Push files to Repo

* In cases where you don't need to push files to Repo, you may replace this section with "Conclusions and Next Steps" and state your conclusions and next steps.

In [ ]:
import os
try:
  # create your folder here
  # os.makedirs(name='')
except Exception as e:
  print(e)