# Cleaning the Dudley Deprivation Dataset

## Purpose
Prepare the deprivation dataset for the Dudley employment barriers project, which explores local factors that may affect people's ability to move into work.

## Objectives
- Inspect the source information, year, structure and geographic coverage.
- Identify the relevant Dudley records and deprivation measures.
- Check missing values, duplicates and data types.
- Check geographic compatibility with the other cleaned datasets.
- Save a validated dataset for later analysis.

## Input
`raw_datasets/dudley_iod.csv`

## Output
`cleaned_datasets/dudley_iod_cleaned.csv`

## Ethical Considerations
Deprivation measures describe areas, not individual circumstances. They should not be used to assume that every resident experiences the same barriers to employment. Source dates and geographic differences will be documented to support responsible interpretation.

## Additional Comments
ChatGPT assisted with planning, code development and documentation.
The original dataset will remain unchanged. This notebook covers cleaning
and validation only; analysis and visualisations will follow separately.

---

# Change working directory

* We are assuming you will store the notebooks in a subfolder, therefore when running the notebook in the editor, you will need to change the working directory

We need to change the working directory from its current folder to its parent folder
* We access the current directory with os.getcwd()

In [1]:
import os
current_dir = os.getcwd()
current_dir

'c:\\Dudley employment barriers\\jupyter_notebooks'

We want to make the parent of the current directory the new current directory
* os.path.dirname() gets the parent directory
* os.chir() defines the new current directory

In [2]:
os.chdir(os.path.dirname(current_dir))
print("You set a new current directory")

You set a new current directory

Confirm the new current directory

In [3]:
current_dir = os.getcwd()
current_dir

'c:\\Dudley employment barriers'

## 1. Inspect the Raw File

Inspect the first ten lines to identify the column headers and any
source information before choosing how to load the dataset.
The original file will remain unchanged.

## Ethical Considerations When Inspecting the Raw IMD Dataset

Inspecting the first ten lines of the raw Index of Multiple Deprivation (IMD) dataset is an important ethical step before loading the data into pandas. This allows the file structure, metadata, and column headings to be examined without modifying the original source file.

### Why Ethical Inspection Matters

The IMD is widely used to identify patterns of deprivation and inequality across neighbourhoods. Because the dataset may influence how communities are described and understood, it is important to verify the file structure before beginning any analysis.

Inspecting the raw file helps to:

- Confirm the source and structure of the dataset.
- Identify metadata and non-data rows.
- Understand column headings and variable definitions.
- Prevent accidental misinterpretation of the data.
- Maintain transparency throughout the cleaning process.

### Ethical Risks if the Raw File Is Not Inspected

If the raw dataset is loaded without inspection, several ethical risks may arise:

- **Misinterpretation of metadata**  
  Non-data rows may be treated as actual records.

- **Incorrect column identification**  
  Variables may be misunderstood, leading to misleading analysis.

- **Data processing errors**  
  Missing header information may cause values to be assigned to the wrong columns.

- **Loss of transparency**  
  Users may be unable to understand how the dataset was prepared.

### Ethical Safeguards Used in This Step

This inspection process includes several responsible practices:

- Viewing the raw file without making any changes.
- Displaying line numbers to identify header locations accurately.
- Checking for metadata, notes, and source information.
- Confirming where the data records begin.
- Retaining the original CSV exactly as provided.

### Why This Matters for Responsible Interpretation

The IMD measures relative deprivation rather than the characteristics of individual people. Care must therefore be taken to avoid stereotyping or making assumptions about residents based solely on neighbourhood-level indicators.

By inspecting the raw file before loading it into the analysis environment, this project promotes transparency, accuracy, and responsible handling of deprivation data.

### Ethical Finding

The raw IMD file was inspected successfully before loading. This confirmed the file structure, identified the correct location of the column headings, and ensured that the original dataset remained unchanged prior to any cleaning or analysis.

In [4]:
# Developed with ChatGPT assistance to inspect the raw file structure.
from itertools import islice

raw_path = "raw_datasets/dudley_iod.csv"

# Display the first ten lines with line numbers.
with open(raw_path, "r", encoding="utf-8-sig") as file:
    for line_number, line in enumerate(islice(file, 10), start=1):
        print(f"{line_number}: {line.rstrip()}")

1: LSOA code (2011),LSOA name (2011),Local Authority District code (2019),Local Authority District name (2019),Index of Multiple Deprivation (IMD) Score,Index of Multiple Deprivation (IMD) Rank (where 1 is most deprived),Index of Multiple Deprivation (IMD) Decile (where 1 is most deprived 10% of LSOAs),Income Score (rate),Income Rank (where 1 is most deprived),Income Decile (where 1 is most deprived 10% of LSOAs),Employment Score (rate),Employment Rank (where 1 is most deprived),Employment Decile (where 1 is most deprived 10% of LSOAs),"Education, Skills and Training Score","Education, Skills and Training Rank (where 1 is most deprived)","Education, Skills and Training Decile (where 1 is most deprived 10% of LSOAs)",Health Deprivation and Disability Score,Health Deprivation and Disability Rank (where 1 is most deprived),Health Deprivation and Disability Decile (where 1 is most deprived 10% of LSOAs),Crime Score,Crime Rank (where 1 is most deprived),Crime Decile (where 1 is most deprived 10% of LSOAs),Barriers to Housing and Services Score,Barriers to Housing and Services Rank (where 1 is most deprived),Barriers to Housing and Services Decile (where 1 is most deprived 10% of LSOAs),Living Environment Score,Living Environment Rank (where 1 is most deprived),Living Environment Decile (where 1 is most deprived 10% of LSOAs),Income Deprivation Affecting Children Index (IDACI) Score (rate),Income Deprivation Affecting Children Index (IDACI) Rank (where 1 is most deprived),Income Deprivation Affecting Children Index (IDACI) Decile (where 1 is most deprived 10% of LSOAs),Income Deprivation Affecting Older People (IDAOPI) Score (rate),Income Deprivation Affecting Older People (IDAOPI) Rank (where 1 is most deprived),Income Deprivation Affecting Older People (IDAOPI) Decile (where 1 is most deprived 10% of LSOAs),Children and Young People Sub-domain Score,Children and Young People Sub-domain Rank (where 1 is most deprived),Children and Young People Sub-domain Decile (where 1 is most deprived 10% of LSOAs),Adult Skills Sub-domain Score,Adult Skills Sub-domain Rank (where 1 is most deprived),Adult Skills Sub-domain Decile (where 1 is most deprived 10% of LSOAs),Geographical Barriers Sub-domain Score,Geographical Barriers Sub-domain Rank (where 1 is most deprived),Geographical Barriers Sub-domain Decile (where 1 is most deprived 10% of LSOAs),Wider Barriers Sub-domain Score,Wider Barriers Sub-domain Rank (where 1 is most deprived),Wider Barriers Sub-domain Decile (where 1 is most deprived 10% of LSOAs),Indoors Sub-domain Score,Indoors Sub-domain Rank (where 1 is most deprived),Indoors Sub-domain Decile (where 1 is most deprived 10% of LSOAs),Outdoors Sub-domain Score,Outdoors Sub-domain Rank (where 1 is most deprived),Outdoors Sub-domain Decile (where 1 is most deprived 10% of LSOAs),Total population: mid 2015 (excluding prisoners),Dependent Children aged 0-15: mid 2015 (excluding prisoners),Population aged 16-59: mid 2015 (excluding prisoners),Older population aged 60 and over: mid 2015 (excluding prisoners),Working age population 18-59/64: for use with Employment Deprivation Domain (excluding prisoners)
2: E01000001,City of London 001A,E09000001,City of London,6.208,29199,9,0.007,32831,10,0.01,32742,10,0.024,32842,10,-1.654,32113,10,-2.012,32662,10,29.472,7319,3,31.873,7789,3,0.006,32806,10,0.012,32820,10,-2.107,32777,10,0.032,32843,10,-0.43,22985,7,3.587,3216,1,0.006,16364,5,1.503,1615,1,1296,175,656,465,715
3: E01000002,City of London 001B,E09000001,City of London,5.143,30379,10,0.034,29901,10,0.027,31190,10,0.063,32832,10,-1.115,29705,10,-2.343,32789,10,24.412,11707,4,23.084,13070,4,0.037,29682,10,0.03,31938,10,-1.907,32666,10,0.034,32841,10,-1.06,30223,10,3.231,3894,2,-0.41,22676,7,1.196,2969,1,1156,182,580,394,620
4: E01000003,City of London 001C,E09000001,City of London,19.402,14915,5,0.086,18510,6,0.086,15103,5,5.804,26386,9,-0.102,17600,6,-1.032,29363,9,40.103,2157,1,40.535,4092,2,0.052,27063,9,0.128,16377,5,-0.292,20837,7,0.142,30999,10,-0.691,26719,9,5.173,818,1,-0.054,17318,6,2.207,162,1,1350,146,759,445,804
5: E01000005,City of London 001E,E09000001,City of London,28.652,8678,3,0.211,6029,2,0.136,7833,3,22.26,12370,4,-0.121,17907,6,-1.317,31059,10,39.9,2217,1,28.979,9397,3,0.209,9458,3,0.322,3885,2,0.338,10914,4,0.321,13658,5,-1.167,30865,10,5.361,672,1,-0.604,25218,8,1.769,849,1,1121,229,692,200,683
6: E01000006,Barking and Dagenham 016A,E09000002,Barking and Dagenham,19.837,14486,5,0.117,14023,5,0.059,21692,7,14.798,17511,6,-0.359,21581,7,-0.147,18848,6,45.171,1033,1,26.888,10629,4,0.155,13592,5,0.162,12934,4,-0.366,21932,7,0.325,13244,5,-0.4,22527,7,5.59,520,1,0.11,14745,5,0.969,4368,2,2040,522,1297,221,1285
7: E01000007,Barking and Dagenham 015A,E09000002,Barking and Dagenham,31.576,7256,3,0.207,6261,2,0.107,11487,4,11.385,20536,7,-0.027,16414,5,0.846,4925,2,50.42,274,1,25.995,11162,4,0.253,6750,3,0.371,2514,1,-0.133,18304,6,0.251,21531,7,-0.951,29432,9,6.897,33,1,-0.28,20820,7,1.324,2319,1,2101,572,1424,105,1404
8: E01000008,Barking and Dagenham 015B,E09000002,Barking and Dagenham,37.596,5010,2,0.265,3382,2,0.151,6431,2,25.506,10569,4,0.25,12334,4,0.353,11113,4,45.413,981,1,30.233,8672,3,0.298,4452,2,0.468,893,1,0.129,14007,5,0.384,7918,3,-0.498,24033,8,5.736,443,1,-0.587,25009,8,1.84,674,1,1566,534,961,71,940
9: E01000009,Barking and Dagenham 016B,E09000002,Barking and Dagenham,32.844,6736,3,0.187,7506,3,0.109,11132,4,15.713,16819,6,0.454,9661,3,0.895,4431,2,48.119,554,1,28.601,9611,3,0.194,10487,4,0.383,2238,1,0.101,14445,5,0.277,18554,6,-1.424,31919,10,6.643,92,1,-0.107,18146,6,1.37,2131,1,1775,356,1190,229,1217
10: E01000010,Barking and Dagenham 015C,E09000002,Barking and Dagenham,32.437,6900,3,0.169,8902,3,0.073,17988,6,11.762,20182,7,-0.002,16050,5,1.214,2164,1,50.58,259,1,47.932,2269,1,0.22,8757,3,0.519,531,1,0.022,15696,5,0.228,24261,8,-1.162,30844,10,7.211,6,1,0.931,4411,2,1.271,2600,1,3195,837,2213,145,2234

### Findings
- Column headers appear on the first line.
- The file includes areas outside Dudley, so filtering is required.
- LSOA codes and names use 2011 geography.
- Local authority columns refer to 2019 boundaries.
- Several population columns refer to mid-2015.
- The deprivation release year needs confirmation from the source;
  geographic dates alone do not establish the release year.
- Geographic compatibility with the Census 2021 datasets must be
  checked before merging.
 
 ---

## 2. Load and Preview the Dataset

Load the CSV using the first row as column headers.
Check the number of rows and columns, then preview five records.
Keep the raw dataframe unchanged for reference.

In [5]:
# Developed with ChatGPT assistance to load and inspect the dataset.
import pandas as pd

# Load the raw CSV without skipping any rows.
iod_df = pd.read_csv(raw_path, encoding="utf-8-sig")

# Check the dataset size and preview five records.
print(f"Rows: {iod_df.shape[0]}")
print(f"Columns: {iod_df.shape[1]}")

display(iod_df.head())

Rows: 32844
Columns: 57

,LSOA code (2011),LSOA name (2011),Local Authority District code (2019),Local Authority District name (2019),Index of Multiple Deprivation (IMD) Score,Index of Multiple Deprivation (IMD) Rank (where 1 is most deprived),Index of Multiple Deprivation (IMD) Decile (where 1 is most deprived 10% of LSOAs),Income Score (rate),Income Rank (where 1 is most deprived),Income Decile (where 1 is most deprived 10% of LSOAs),...,Indoors Sub-domain Rank (where 1 is most deprived),Indoors Sub-domain Decile (where 1 is most deprived 10% of LSOAs),Outdoors Sub-domain Score,Outdoors Sub-domain Rank (where 1 is most deprived),Outdoors Sub-domain Decile (where 1 is most deprived 10% of LSOAs),Total population: mid 2015 (excluding prisoners),Dependent Children aged 0-15: mid 2015 (excluding prisoners),Population aged 16-59: mid 2015 (excluding prisoners),Older population aged 60 and over: mid 2015 (excluding prisoners),Working age population 18-59/64: for use with Employment Deprivation Domain (excluding prisoners)
0,E01000001,City of London 001A,E09000001,City of London,6.208,29199,9,0.007,32831,10,...,16364,5,1.503,1615,1,1296,175,656,465,715
1,E01000002,City of London 001B,E09000001,City of London,5.143,30379,10,0.034,29901,10,...,22676,7,1.196,2969,1,1156,182,580,394,620
2,E01000003,City of London 001C,E09000001,City of London,19.402,14915,5,0.086,18510,6,...,17318,6,2.207,162,1,1350,146,759,445,804
3,E01000005,City of London 001E,E09000001,City of London,28.652,8678,3,0.211,6029,2,...,25218,8,1.769,849,1,1121,229,692,200,683
4,E01000006,Barking and Dagenham 016A,E09000002,Barking and Dagenham,19.837,14486,5,0.117,14023,5,...,14745,5,0.969,4368,2,2040,522,1297,221,1285

### Findings
- The dataset loaded successfully with 32,844 rows and 57 columns.
- The five-row preview shows geographic identifiers, deprivation
  measures and population figures in separate columns.
- Records include City of London and Barking and Dagenham,
  confirming that the file is not restricted to Dudley.
- The raw dataset is retained in `iod_df`; no filtering or
  cleaning has been applied.

---

## 3. Select Dudley Records

Select records where the local authority district name is Dudley.
Create a separate copy so the full raw dataframe remains unchanged.
Check the number of selected records and preview five rows.

## Ethical Considerations When Selecting Dudley Records

This step filters the national IMD dataset to retain only records belonging to Dudley. Creating a separate copy ensures that the original dataset remains unchanged while providing a focused dataset for local analysis.

### Why Ethical Filtering Matters

The original dataset contains records for neighbourhoods across England. Since this project focuses specifically on employment barriers within Dudley, it is important to isolate only the relevant local authority records before further analysis.

Selecting the correct geographical area helps to:

- Ensure that findings accurately reflect Dudley neighbourhoods.
- Prevent unrelated areas from influencing results.
- Support fair comparisons between Dudley LSOAs.
- Improve transparency in the data preparation process.
- Maintain consistency with other Dudley-based datasets used in this project.

### Ethical Risks if Records Are Not Filtered Correctly

If geographic records are selected incorrectly, several ethical risks may arise:

- **Misrepresentation of local conditions**  
  Including records from other local authorities may distort deprivation measures for Dudley.

- **Biased findings**  
  Analysis could reflect national or regional patterns rather than local circumstances.

- **Incorrect resource implications**  
  Conclusions about disadvantage or employment barriers may not accurately represent Dudley communities.

- **Loss of transparency**  
  Users may be unable to understand which geographical area the results actually describe.

### Ethical Safeguards Used in This Step

This filtering process includes several responsible practices:

- Selecting records using the official local authority name.
- Creating a separate copy so the original dataset remains unchanged.
- Checking the number of retained records.
- Verifying the local authority code after filtering.
- Reviewing sample rows to confirm that only Dudley records remain.

### Why This Matters for Responsible Interpretation

The Index of Multiple Deprivation measures relative deprivation at neighbourhood level. To draw fair and meaningful conclusions, the dataset must represent the correct geographic area.

By selecting only Dudley records, this project reduces the risk of geographic bias, improves accuracy, and ensures that subsequent analysis focuses on the communities relevant to the research objectives.

### Ethical Finding

Only records belonging to Dudley were retained for analysis. The filtered dataset contains the expected Dudley local authority identifier and preserves all original columns required for later stages of the project. The original national dataset remains unchanged and available for auditing purposes.

In [6]:
# Developed with ChatGPT assistance to select Dudley records.

# Filter by the local authority name and retain all columns.
dudley_mask = (
    iod_df["Local Authority District name (2019)"] == "Dudley"
)
iod_clean = iod_df.loc[dudley_mask].copy().reset_index(drop=True)

# Check the selected dataset size and local authority code.
print(f"Dudley rows: {iod_clean.shape[0]}")
print(f"Columns: {iod_clean.shape[1]}")
print(
    "Local authority codes:",
    iod_clean["Local Authority District code (2019)"].unique()
)

display(iod_clean.head())

Dudley rows: 201
Columns: 57
Local authority codes: ['E08000027']

,LSOA code (2011),LSOA name (2011),Local Authority District code (2019),Local Authority District name (2019),Index of Multiple Deprivation (IMD) Score,Index of Multiple Deprivation (IMD) Rank (where 1 is most deprived),Index of Multiple Deprivation (IMD) Decile (where 1 is most deprived 10% of LSOAs),Income Score (rate),Income Rank (where 1 is most deprived),Income Decile (where 1 is most deprived 10% of LSOAs),...,Indoors Sub-domain Rank (where 1 is most deprived),Indoors Sub-domain Decile (where 1 is most deprived 10% of LSOAs),Outdoors Sub-domain Score,Outdoors Sub-domain Rank (where 1 is most deprived),Outdoors Sub-domain Decile (where 1 is most deprived 10% of LSOAs),Total population: mid 2015 (excluding prisoners),Dependent Children aged 0-15: mid 2015 (excluding prisoners),Population aged 16-59: mid 2015 (excluding prisoners),Older population aged 60 and over: mid 2015 (excluding prisoners),Working age population 18-59/64: for use with Employment Deprivation Domain (excluding prisoners)
0,E01009719,Dudley 027A,E08000027,Dudley,19.002,15243,5,0.092,17610,6,...,2099,1,0.124,13252,5,1438,281,807,350,801
1,E01009720,Dudley 028A,E08000027,Dudley,5.745,29752,10,0.038,29138,9,...,28075,9,-0.288,20154,7,1391,244,821,326,839
2,E01009721,Dudley 031A,E08000027,Dudley,21.239,13372,5,0.151,10410,4,...,12971,4,-0.339,21016,7,2030,349,1173,508,1192
3,E01009722,Dudley 027B,E08000027,Dudley,11.606,22637,7,0.061,23560,8,...,8578,3,-0.034,15848,5,1365,215,695,455,718
4,E01009723,Dudley 028B,E08000027,Dudley,5.036,30469,10,0.036,29540,9,...,29616,10,-0.456,22860,7,1237,215,722,300,745

### Findings
- Filtering selected 201 Dudley records and retained all 57 columns.
- All selected records have local authority code `E08000027`.
- The five-row preview shows Dudley LSOA names.
- The selected data is stored separately in `iod_clean`, leaving
  `iod_df` unchanged.
- The row count differs from the 203 rows in the cleaned Census
  datasets. The LSOA codes and boundary differences need checking
  before merging; this does not yet establish missing data.

---

## 4. Check Missing Values and Duplicates

Check the Dudley subset for missing values, duplicate rows and
repeated LSOA codes. Confirm the number of unique codes before
comparing geographic coverage with the Census datasets.

## Ethical Considerations When Checking Missing Values and Duplicates

This step evaluates the quality and completeness of the Dudley IMD dataset by identifying missing values, duplicate records, and repeated LSOA codes. These checks help ensure that each neighbourhood is represented accurately before deprivation measures are used in further analysis.

### Why Ethical Data Quality Checks Matter

The Index of Multiple Deprivation is often used to identify areas experiencing greater social and economic disadvantage. Because these measures may influence how neighbourhoods are described and interpreted, it is important to verify that the dataset is complete and free from duplication.

Data quality checks help to:

- Ensure fair representation of all neighbourhoods.
- Identify potential errors before analysis begins.
- Prevent duplicate records from biasing results.
- Support transparency and reproducibility.
- Improve confidence in later findings.

### Ethical Risks if Data Quality Is Not Checked

If missing values or duplicates are not identified, several ethical risks may arise:

- **Misrepresentation of neighbourhoods**  
  Missing values may create an incomplete picture of deprivation.

- **Biased analysis**  
  Duplicate records may give certain areas greater influence over summary statistics.

- **Incorrect comparisons**  
  Repeated LSOA codes could distort rankings and deprivation patterns.

- **Misleading conclusions**  
  Decisions based on poor-quality data may not accurately reflect local needs.

### Ethical Safeguards Used in This Step

This validation process includes several responsible practices:

- Checking all columns for missing values.
- Identifying duplicate records across the dataset.
- Verifying that each LSOA code appears only once.
- Counting unique LSOA codes before geographic comparisons.
- Documenting any issues before moving to later stages of the analysis.

### Why This Matters for Responsible Interpretation

Deprivation statistics describe neighbourhood-level conditions rather than individual people. Accurate and complete geographic records are therefore essential to avoid biased findings and ensure that each community is represented fairly.

By checking for missing values and duplicate records, this project supports transparency, data integrity, and responsible analysis of deprivation patterns across Dudley.

### Ethical Finding

The dataset was assessed for missing values, duplicate rows, and repeated LSOA codes before further analysis. Verifying data completeness and uniqueness reduces the risk of bias and helps ensure that deprivation measures are interpreted consistently across all Dudley neighbourhoods.

In [7]:
# Developed with ChatGPT assistance to check data completeness.

# Show only columns containing missing values.
missing_values = iod_clean.isna().sum()
print("Columns with missing values:")
print(missing_values[missing_values > 0].to_string())

# Check duplicate records and geographic identifiers.
print("\nDuplicate rows:", iod_clean.duplicated().sum())
print(
    "Duplicate LSOA codes:",
    iod_clean["LSOA code (2011)"].duplicated().sum()
)
print(
    "Unique LSOA codes:",
    iod_clean["LSOA code (2011)"].nunique()
)

Columns with missing values:
Series([], )

Duplicate rows: 0
Duplicate LSOA codes: 0
Unique LSOA codes: 201

### Findings
- No missing values were detected across the 57 columns.
- No duplicate rows or duplicate LSOA codes were found.
- The Dudley subset contains 201 unique LSOA codes.
- No missing-value treatment or duplicate removal is required.

---

## 5. Compare LSOA Codes with the Census Dataset

Compare the deprivation dataset's 2011 LSOA codes with the codes
in the cleaned economic activity dataset.

Identify shared codes and codes appearing in only one dataset.
This is an initial compatibility check; it does not by itself
confirm that geographic boundaries are identical.

## Ethical Considerations When Comparing LSOA Codes with the Census Dataset

This step compares the LSOA codes in the Dudley IMD dataset with those in the cleaned Census economic activity dataset. The purpose is to identify shared geographic areas and investigate any LSOAs that appear in only one dataset before attempting to combine data sources.

### Why Ethical Geographic Comparisons Matter

Accurate geographic matching is essential when combining datasets that describe different aspects of the same communities. If neighbourhood boundaries or codes differ between datasets, any analysis based on merged data may produce misleading results.

Comparing LSOA coverage helps to:

- Ensure that datasets describe the same neighbourhoods.
- Identify boundary or classification differences.
- Reduce the risk of geographic bias.
- Support accurate dataset integration.
- Improve transparency before analysis and visualisation.

### Ethical Risks if Geographic Coverage Is Not Compared

If geographic compatibility is not checked before merging datasets, several ethical risks may arise:

- **Neighbourhood exclusion**  
  Some communities may be omitted from the final analysis without being identified.

- **Incorrect matching of records**  
  Data from different areas may be linked together, producing misleading results.

- **Biased findings**  
  Differences in geographic coverage may distort relationships between deprivation, employment, disability, qualifications, or transport access.

- **Misleading conclusions**  
  Stakeholders may assume results reflect all Dudley neighbourhoods when some areas are missing.

### Ethical Safeguards Used in This Step

This comparison process includes several responsible practices:

- Comparing unique LSOA codes across datasets.
- Identifying shared neighbourhoods before merging.
- Detecting LSOAs that appear in only one dataset.
- Displaying unmatched areas for investigation.
- Documenting any differences in coverage before analytical decisions are made.

### Why This Matters for Responsible Interpretation

Deprivation indicators and Census measures can only be compared fairly when they refer to the same geographical units. Any differences in LSOA coverage must be understood before conclusions are drawn about employment barriers or deprivation.

By comparing geographic coverage before merging datasets, this project promotes transparency, reduces the risk of misleading comparisons, and supports responsible interpretation of neighbourhood-level data.

### Ethical Finding

The geographic coverage of the IMD and Census datasets was compared using LSOA codes. Shared areas and unmatched areas were identified and documented for investigation. This validation step helps ensure that future dataset merges are carried out accurately and that any differences in geographic coverage are understood before analysis proceeds.

In [8]:
# Developed with ChatGPT assistance to compare geographic coverage.

# Load the cleaned Census economic activity dataset.
economic_df = pd.read_csv(
    "cleaned_datasets/dudley_economic_activity_cleaned.csv"
)

# Compare unique LSOA codes from the two datasets.
iod_codes = set(iod_clean["LSOA code (2011)"])
census_codes = set(economic_df["LSOA_Code"])

print("Shared LSOA codes:", len(iod_codes & census_codes))
print("Codes only in deprivation data:", len(iod_codes - census_codes))
print("Codes only in Census data:", len(census_codes - iod_codes))

# Display the areas requiring further investigation.
print("\nAreas only in deprivation data:")
display(
    iod_clean.loc[
        iod_clean["LSOA code (2011)"].isin(iod_codes - census_codes),
        ["LSOA code (2011)", "LSOA name (2011)"]
    ]
)

print("\nAreas only in Census data:")
display(
    economic_df.loc[
        economic_df["LSOA_Code"].isin(census_codes - iod_codes),
        ["LSOA_Code", "LSOA_Name"]
    ]
)

Shared LSOA codes: 199
Codes only in deprivation data: 2
Codes only in Census data: 4

Areas only in deprivation data:

    LSOA code (2011) LSOA name (2011)
160        E01009881      Dudley 011C
200        E01033187      Dudley 006G

Areas only in Census data:

    LSOA_Code    LSOA_Name
29  E01034306  Dudley 006H
30  E01034307  Dudley 006I
53  E01034308  Dudley 011E
54  E01034309  Dudley 011F

### Findings
- The datasets share 199 LSOA codes.
- Two codes appear only in the deprivation dataset:
  - `E01009881` — Dudley 011C.
  - `E01033187` — Dudley 006G.
- Four codes appear only in the Census dataset:
  - `E01034306` — Dudley 006H.
  - `E01034307` — Dudley 006I.
  - `E01034308` — Dudley 011E.
  - `E01034309` — Dudley 011F.
- A direct inner merge would retain only the 199 shared codes,
  excluding four Census areas.
- The area names suggest possible boundary splits, but an official
  lookup is needed to confirm the relationships.
- Geographic differences require investigation before deciding
  how to combine the datasets. No records have been removed.

---

## 6. Inspect Column Data Types

Inspect the data type of every column before selecting or renaming
variables. Geographic identifiers should remain text, while
deprivation measures and population figures should be numeric.

Scores, ranks, deciles and population counts represent different
types of measurements and will require different validation rules.

## Ethical Considerations When Inspecting Column Data Types

This step examines the data type assigned to each column before any variables are selected, renamed, or transformed. Understanding how information is stored is important because deprivation measures, geographic identifiers, rankings, and population figures represent different kinds of data and require different handling procedures.

### Why Ethical Data-Type Validation Matters

The IMD dataset contains a mixture of:

- Geographic identifiers
- Neighbourhood names
- Deprivation scores
- Deprivation ranks
- Deciles
- Population counts

Each variable serves a different purpose and should be stored in an appropriate format. Verifying data types before cleaning helps ensure that information is interpreted correctly and reduces the risk of introducing errors during analysis.

### Ethical Risks if Data Types Are Not Checked

If data types are assumed rather than verified, several ethical risks may arise:

- **Misinterpretation of variables**  
  Geographic identifiers stored as numbers could lose leading zeros and become invalid.

- **Incorrect statistical analysis**  
  Text variables may be treated as numeric values, producing misleading results.

- **Data integrity issues**  
  Numeric indicators stored as text may prevent accurate calculations and comparisons.

- **Biased findings**  
  Errors in processing deprivation measures may affect how neighbourhoods are represented.

### Ethical Safeguards Used in This Step

This validation process includes several responsible practices:

- Reviewing the data type assigned to every column.
- Identifying variables currently stored as text.
- Confirming that geographic identifiers remain as text values.
- Verifying that deprivation measures and population statistics are stored numerically where appropriate.
- Documenting any data-type issues before further cleaning or transformation.

### Why This Matters for Responsible Interpretation

The IMD dataset is used to understand relative deprivation across neighbourhoods. Accurate interpretation depends on preserving the meaning of each variable and ensuring that calculations are performed on appropriate data types.

By inspecting column data types before analysis, this project supports transparency, data integrity, and responsible use of deprivation statistics.

### Ethical Finding

All column data types were reviewed before any transformations were applied. Geographic identifiers were checked to ensure they remained text values, while deprivation measures and population variables were assessed for suitability as numeric data. This validation step helps reduce processing errors and promotes accurate interpretation of deprivation indicators.

In [9]:
# Developed with ChatGPT assistance to inspect column data types.

# Display every column and its current data type.
print(iod_clean.dtypes.to_string())

# Identify columns currently stored as text.
text_columns = iod_clean.select_dtypes(include="object").columns

print("\nText columns:")
for column in text_columns:
    print(column)

LSOA code (2011)                                                                                       object
LSOA name (2011)                                                                                       object
Local Authority District code (2019)                                                                   object
Local Authority District name (2019)                                                                   object
Index of Multiple Deprivation (IMD) Score                                                             float64
Index of Multiple Deprivation (IMD) Rank (where 1 is most deprived)                                     int64
Index of Multiple Deprivation (IMD) Decile (where 1 is most deprived 10% of LSOAs)                      int64
Income Score (rate)                                                                                   float64
Income Rank (where 1 is most deprived)                                                                  int64
Income Decile (where 1 is most deprived 10% of LSOAs)                                                   int64
Employment Score (rate)                                                                               float64
Employment Rank (where 1 is most deprived)                                                              int64
Employment Decile (where 1 is most deprived 10% of LSOAs)                                               int64
Education, Skills and Training Score                                                                  float64
Education, Skills and Training Rank (where 1 is most deprived)                                          int64
Education, Skills and Training Decile (where 1 is most deprived 10% of LSOAs)                           int64
Health Deprivation and Disability Score                                                               float64
Health Deprivation and Disability Rank (where 1 is most deprived)                                       int64
Health Deprivation and Disability Decile (where 1 is most deprived 10% of LSOAs)                        int64
Crime Score                                                                                           float64
Crime Rank (where 1 is most deprived)                                                                   int64
Crime Decile (where 1 is most deprived 10% of LSOAs)                                                    int64
Barriers to Housing and Services Score                                                                float64
Barriers to Housing and Services Rank (where 1 is most deprived)                                        int64
Barriers to Housing and Services Decile (where 1 is most deprived 10% of LSOAs)                         int64
Living Environment Score                                                                              float64
Living Environment Rank (where 1 is most deprived)                                                      int64
Living Environment Decile (where 1 is most deprived 10% of LSOAs)                                       int64
Income Deprivation Affecting Children Index (IDACI) Score (rate)                                      float64
Income Deprivation Affecting Children Index (IDACI) Rank (where 1 is most deprived)                     int64
Income Deprivation Affecting Children Index (IDACI) Decile (where 1 is most deprived 10% of LSOAs)      int64
Income Deprivation Affecting Older People (IDAOPI) Score (rate)                                       float64
Income Deprivation Affecting Older People (IDAOPI) Rank (where 1 is most deprived)                      int64
Income Deprivation Affecting Older People (IDAOPI) Decile (where 1 is most deprived 10% of LSOAs)       int64
Children and Young People Sub-domain Score                                                            float64
Children and Young People Sub-domain Rank (where 1 is most deprived)                                    int64
Children and Young People Sub-domain Decile (where 1 is most deprived 10% of LSOAs)                     int64
Adult Skills Sub-domain Score                                                                         float64
Adult Skills Sub-domain Rank (where 1 is most deprived)                                                 int64
Adult Skills Sub-domain Decile (where 1 is most deprived 10% of LSOAs)                                  int64
Geographical Barriers Sub-domain Score                                                                float64
Geographical Barriers Sub-domain Rank (where 1 is most deprived)                                        int64
Geographical Barriers Sub-domain Decile (where 1 is most deprived 10% of LSOAs)                         int64
Wider Barriers Sub-domain Score                                                                       float64
Wider Barriers Sub-domain Rank (where 1 is most deprived)                                               int64
Wider Barriers Sub-domain Decile (where 1 is most deprived 10% of LSOAs)                                int64
Indoors Sub-domain Score                                                                              float64
Indoors Sub-domain Rank (where 1 is most deprived)                                                      int64
Indoors Sub-domain Decile (where 1 is most deprived 10% of LSOAs)                                       int64
Outdoors Sub-domain Score                                                                             float64
Outdoors Sub-domain Rank (where 1 is most deprived)                                                     int64
Outdoors Sub-domain Decile (where 1 is most deprived 10% of LSOAs)                                      int64
Total population: mid 2015 (excluding prisoners)                                                        int64
Dependent Children aged 0-15: mid 2015 (excluding prisoners)                                            int64
Population aged 16-59: mid 2015 (excluding prisoners)                                                   int64
Older population aged 60 and over: mid 2015 (excluding prisoners)                                       int64
Working age population 18-59/64: for use with Employment Deprivation Domain (excluding prisoners)       int64

Text columns:
LSOA code (2011)
LSOA name (2011)
Local Authority District code (2019)
Local Authority District name (2019)

### Findings
- The four geographic code and name columns are stored as text
  (`object`), preserving their identifiers.
- Deprivation scores and rates are stored as decimal numbers
  (`float64`).
- Ranks, deciles and population counts are stored as integers
  (`int64`).
- No numeric measure columns were loaded as text, so no data type
  conversions are needed at this stage.
- Numeric ranges still need validation; correct data types alone
  do not confirm that the values are valid.

---

## 7. Validate Ranks and Deciles

Check that ranks fall between 1 and the number of records in the
full source dataset (32,844), and that deciles fall between 1 and 10.

Use the full dataset size because these rankings compare areas
nationally, rather than only within Dudley. Retain the original
rank and decile values.

## Ethical Considerations When Validating Ranks and Deciles

This step validates the rank and decile measures within the Dudley IMD dataset. These indicators are used to compare neighbourhoods nationally, so it is important to verify that all values fall within the expected ranges before any analysis is undertaken.

### Why Ethical Validation Matters

The IMD ranks and deciles are designed to indicate relative deprivation across England. Because these measures may influence how neighbourhoods are compared and interpreted, it is important to confirm that the values are valid and consistent with the official methodology.

Validating these measures helps to:

- Confirm that deprivation indicators have been loaded correctly.
- Detect potential data-entry or processing errors.
- Support fair comparisons between neighbourhoods.
- Maintain confidence in subsequent analysis.
- Improve transparency within the data-cleaning process.

### Ethical Risks if Ranks and Deciles Are Not Validated

If rank and decile values are not checked, several ethical risks may arise:

- **Misrepresentation of neighbourhoods**  
  Invalid values could incorrectly indicate levels of deprivation.

- **Misleading comparisons**  
  Areas could appear more or less deprived than they actually are.

- **Biased findings**  
  Statistical summaries and visualisations may be distorted by incorrect values.

- **Incorrect policy interpretation**  
  Decisions based on inaccurate deprivation measures may not reflect genuine local needs.

### Ethical Safeguards Used in This Step

This validation process includes several responsible practices:

- Identifying all rank variables automatically.
- Identifying all decile variables automatically.
- Checking that ranks fall within the valid national range.
- Checking that deciles fall between 1 and 10.
- Reporting any values that fall outside the expected limits.
- Retaining all original values without modification.

### Why This Matters for Responsible Interpretation

IMD ranks and deciles describe relative deprivation rather than individual circumstances. Accurate values are therefore essential to ensure that neighbourhoods are compared fairly and interpreted responsibly.

By validating rank and decile ranges before analysis, this project helps prevent errors, reduce bias, and support transparent and trustworthy reporting of deprivation patterns across Dudley.

### Ethical Finding

All rank and decile columns were checked against their expected value ranges. This validation confirms that the deprivation indicators are structurally consistent with the national IMD methodology and suitable for further analysis, provided no out-of-range values are identified.

In [10]:
# Developed with ChatGPT assistance to validate ranks and deciles.

# Identify rank and decile columns using their existing names.
rank_columns = [
    column for column in iod_clean.columns if " Rank " in column
]
decile_columns = [
    column for column in iod_clean.columns if " Decile " in column
]

# Count values outside the expected ranges in each column.
invalid_ranks = iod_clean[rank_columns].apply(
    lambda column: (~column.between(1, len(iod_df))).sum()
)
invalid_deciles = iod_clean[decile_columns].apply(
    lambda column: (~column.between(1, 10)).sum()
)

print(f"Rank columns checked: {len(rank_columns)}")
print("Out-of-range ranks:")
print(invalid_ranks.to_string())

print(f"\nDecile columns checked: {len(decile_columns)}")
print("Out-of-range deciles:")
print(invalid_deciles.to_string())

Rank columns checked: 16
Out-of-range ranks:
Index of Multiple Deprivation (IMD) Rank (where 1 is most deprived)                    0
Income Rank (where 1 is most deprived)                                                 0
Employment Rank (where 1 is most deprived)                                             0
Education, Skills and Training Rank (where 1 is most deprived)                         0
Health Deprivation and Disability Rank (where 1 is most deprived)                      0
Crime Rank (where 1 is most deprived)                                                  0
Barriers to Housing and Services Rank (where 1 is most deprived)                       0
Living Environment Rank (where 1 is most deprived)                                     0
Income Deprivation Affecting Children Index (IDACI) Rank (where 1 is most deprived)    0
Income Deprivation Affecting Older People (IDAOPI) Rank (where 1 is most deprived)     0
Children and Young People Sub-domain Rank (where 1 is most deprived)                   0
Adult Skills Sub-domain Rank (where 1 is most deprived)                                0
Geographical Barriers Sub-domain Rank (where 1 is most deprived)                       0
Wider Barriers Sub-domain Rank (where 1 is most deprived)                              0
Indoors Sub-domain Rank (where 1 is most deprived)                                     0
Outdoors Sub-domain Rank (where 1 is most deprived)                                    0

Decile columns checked: 16
Out-of-range deciles:
Index of Multiple Deprivation (IMD) Decile (where 1 is most deprived 10% of LSOAs)                    0
Income Decile (where 1 is most deprived 10% of LSOAs)                                                 0
Employment Decile (where 1 is most deprived 10% of LSOAs)                                             0
Education, Skills and Training Decile (where 1 is most deprived 10% of LSOAs)                         0
Health Deprivation and Disability Decile (where 1 is most deprived 10% of LSOAs)                      0
Crime Decile (where 1 is most deprived 10% of LSOAs)                                                  0
Barriers to Housing and Services Decile (where 1 is most deprived 10% of LSOAs)                       0
Living Environment Decile (where 1 is most deprived 10% of LSOAs)                                     0
Income Deprivation Affecting Children Index (IDACI) Decile (where 1 is most deprived 10% of LSOAs)    0
Income Deprivation Affecting Older People (IDAOPI) Decile (where 1 is most deprived 10% of LSOAs)     0
Children and Young People Sub-domain Decile (where 1 is most deprived 10% of LSOAs)                   0
Adult Skills Sub-domain Decile (where 1 is most deprived 10% of LSOAs)                                0
Geographical Barriers Sub-domain Decile (where 1 is most deprived 10% of LSOAs)                       0
Wider Barriers Sub-domain Decile (where 1 is most deprived 10% of LSOAs)                              0
Indoors Sub-domain Decile (where 1 is most deprived 10% of LSOAs)                                     0
Outdoors Sub-domain Decile (where 1 is most deprived 10% of LSOAs)                                    0

### Findings
- All 16 rank columns were checked across the 201 Dudley records.
- No ranks fall outside the expected range of 1 to 32,844.
- All 16 decile columns were checked.
- No deciles fall outside the expected range of 1 to 10.
- No corrections were required. Original ranks and deciles have
  been retained without recalculating them for Dudley.

---

## 8. Validate Explicit Rate Columns

Check that columns labelled `Score (rate)` contain values between
0 and 1, representing proportions.

Apply this check only to explicitly labelled rates. Other deprivation
scores use different scales and must not be treated as proportions.
Keep the original values unchanged.

## Ethical Considerations When Validating Explicit Rate Columns

This step validates all columns explicitly labelled as rate measures within the IMD dataset. These variables represent proportions and should therefore contain values between 0 and 1. Confirming that the rates fall within the expected range helps ensure accurate interpretation and prevents invalid values from influencing later analysis.

### Why Ethical Validation Matters

Rate measures are used to compare neighbourhoods consistently regardless of population size. Because these figures contribute to assessments of deprivation and disadvantage, it is important to verify that the values are stored and interpreted correctly.

Validating rate columns helps to:

- Confirm that proportion-based indicators are valid.
- Detect data-entry or processing errors.
- Improve confidence in deprivation measures.
- Support fair comparisons between neighbourhoods.
- Maintain transparency in the data-cleaning process.

### Ethical Risks if Rate Columns Are Not Validated

If rate measures are not checked, several ethical risks may arise:

- **Misrepresentation of neighbourhood conditions**  
  Invalid rates may exaggerate or understate levels of deprivation.

- **Misleading comparisons**  
  Areas could appear significantly different due to incorrect values rather than genuine differences.

- **Biased findings**  
  Statistical summaries and visualisations may be distorted by invalid rates.

- **Incorrect interpretation**  
  Values outside the expected range may indicate data quality issues that affect conclusions.

### Ethical Safeguards Used in This Step

This validation process includes several responsible practices:

- Selecting only columns explicitly labelled as rate measures.
- Checking minimum and maximum values for each rate column.
- Verifying that all values fall between 0 and 1.
- Counting any values outside the expected range.
- Retaining all original values without modification.

### Why This Matters for Responsible Interpretation

Rate measures describe proportions rather than counts and must be interpreted differently from deprivation scores, ranks, or population figures. Validating these values helps ensure that neighbourhoods are compared fairly and that deprivation indicators are used appropriately.

By checking explicit rate columns before analysis, this project supports transparency, data quality, and responsible interpretation of deprivation measures across Dudley.

### Ethical Finding

All explicitly labelled rate columns were assessed to confirm that their values fall within the expected range of 0 to 1. This validation helps ensure that proportion-based deprivation indicators remain consistent with their intended interpretation and are suitable for further analysis.

In [11]:
# Developed with ChatGPT assistance to validate explicit rate columns.

# Select only columns explicitly labelled as rates.
rate_columns = [
    column for column in iod_clean.columns
    if "Score (rate)" in column
]

# Summarise the range and count invalid values for each rate.
rate_checks = pd.DataFrame({
    "Minimum": iod_clean[rate_columns].min(),
    "Maximum": iod_clean[rate_columns].max(),
    "Outside_0_to_1": iod_clean[rate_columns].apply(
        lambda column: (~column.between(0, 1)).sum()
    )
})

print(f"Rate columns checked: {len(rate_columns)}")
display(rate_checks)

Rate columns checked: 4

,Minimum,Maximum,Outside_0_to_1
Income Score (rate),0.020,0.408,0
Employment Score (rate),0.021,0.302,0
Income Deprivation Affecting Children Index (IDACI) Score (rate),0.014,0.573,0
Income Deprivation Affecting Older People (IDAOPI) Score (rate),0.027,0.451,0

### Findings
- All four explicitly labelled rate columns contain values between
  0 and 1, with no out-of-range values.
- Observed ranges are:
  - Income: 0.020–0.408.
  - Employment: 0.021–0.302.
  - Income Deprivation Affecting Children (IDACI): 0.014–0.573.
  - Income Deprivation Affecting Older People (IDAOPI): 0.027–0.451.
- No corrections were required. Rates remain in their original
  proportion format.

---

## 9. Validate Population Counts

Check the five population columns for negative or fractional values.
Population counts should be non-negative whole numbers.

These columns describe different population groups. Do not add them
all together, because the working-age population overlaps other groups.

## Ethical Considerations When Validating Population Counts

This step validates the population-related columns within the IMD dataset by checking for negative and fractional values. Population figures should represent counts of people and therefore are expected to be non-negative whole numbers.

### Why Ethical Validation Matters

Population measures provide important context for understanding deprivation patterns and the scale of different demographic groups within each neighbourhood. Ensuring that these figures are valid helps maintain the accuracy and credibility of subsequent analysis.

Validating population counts helps to:

- Confirm that population figures are realistic.
- Detect potential data-entry or processing errors.
- Improve confidence in deprivation indicators that rely on population measures.
- Support fair comparisons between neighbourhoods.
- Maintain transparency throughout the data-cleaning process.

### Ethical Risks if Population Counts Are Not Validated

If population values are not checked, several ethical risks may arise:

- **Misrepresentation of neighbourhood characteristics**  
  Invalid population counts may distort the apparent size of demographic groups.

- **Biased analysis**  
  Incorrect values could influence statistical summaries and visualisations.

- **Misleading conclusions**  
  Relationships between deprivation and population characteristics may be interpreted inaccurately.

- **Reduced data quality**  
  Errors within population measures may undermine confidence in the wider dataset.

### Ethical Safeguards Used in This Step

This validation process includes several responsible practices:

- Identifying all population-related columns systematically.
- Checking for negative values that would be impossible in population counts.
- Checking for fractional values where whole numbers are expected.
- Reviewing minimum and maximum population values.
- Retaining all original values without modification.

### Why This Matters for Responsible Interpretation

Population figures describe groups of residents rather than individual people. These measures provide important context for deprivation analysis but should not be used to make assumptions about specific individuals or communities.

The working-age population overlaps with other population groups, meaning the columns should not be summed together. Understanding these relationships helps prevent misinterpretation and supports responsible use of demographic information.

### Ethical Finding

All identified population columns were assessed for negative and fractional values. The validation confirmed that population counts remain within plausible ranges and are recorded as whole numbers. No corrections were required, supporting the reliability of the demographic information used in later stages of the analysis.

In [12]:
# Developed with ChatGPT assistance to validate population counts.

# Identify population columns from their existing names.
population_columns = [
    column for column in iod_clean.columns
    if "population" in column.lower()
    or column.startswith("Dependent Children")
]

# Check each column without changing the original values.
population_checks = pd.DataFrame({
    "Minimum": iod_clean[population_columns].min(),
    "Maximum": iod_clean[population_columns].max(),
    "Negative_values": (
        iod_clean[population_columns] < 0
    ).sum(),
    "Fractional_values": (
        iod_clean[population_columns] % 1 != 0
    ).sum()
})

print(f"Population columns checked: {len(population_columns)}")
display(population_checks)

Population columns checked: 5

,Minimum,Maximum,Negative_values,Fractional_values
Total population: mid 2015 (excluding prisoners),1139,3122,0,0
Dependent Children aged 0-15: mid 2015 (excluding prisoners),152,1038,0,0
Population aged 16-59: mid 2015 (excluding prisoners),526,1700,0,0
Older population aged 60 and over: mid 2015 (excluding prisoners),176,653,0,0
Working age population 18-59/64: for use with Employment Deprivation Domain (excluding prisoners),539,1673,0,0

### Findings
- All five population columns were checked across the Dudley subset.
- No negative or fractional values were found.
- Total population values range from 1,139 to 3,122 per area.
- All five columns already use the integer data type (`int64`),
  so no conversion or rounding is required.
- The original population counts have been retained unchanged.

---

## 10. Check Population Totals

Check whether the three non-overlapping age groups—0–15, 16–59
and 60 and over—sum to the stated mid-2015 total population.

Exclude the employment-domain working-age population from this sum
because it overlaps these age groups. Report any differences without
changing the original counts.

## Ethical Considerations When Checking Population Totals

This step validates whether the three non-overlapping age-group populations sum to the reported total population for each Dudley neighbourhood. Verifying these relationships helps ensure that the dataset remains internally consistent before deprivation measures are analysed or merged with other datasets.

### Why Ethical Validation Matters

Population figures provide important context for understanding deprivation levels across neighbourhoods. If the relationship between age groups and the total population is incorrect, this may indicate data quality issues that could affect interpretation.

Checking population totals helps to:

- Confirm internal consistency within the dataset.
- Detect potential data-entry or processing errors.
- Improve confidence in demographic information.
- Support fair comparisons between neighbourhoods.
- Maintain transparency throughout the cleaning process.

### Ethical Risks if Population Totals Are Not Checked

If population totals are not validated, several ethical risks may arise:

- **Misrepresentation of neighbourhood characteristics**  
  Inconsistent totals may create an inaccurate picture of local populations.

- **Misleading analysis**  
  Demographic patterns may be interpreted incorrectly if age-group figures do not align with overall population counts.

- **Biased findings**  
  Population inconsistencies could influence deprivation summaries and comparisons.

- **Reduced confidence in data quality**  
  Undetected discrepancies may affect trust in later analysis and reporting.

### Ethical Safeguards Used in This Step

This validation process includes several responsible practices:

- Using only the three non-overlapping age groups to calculate totals.
- Excluding the employment-domain working-age population because it overlaps other age categories.
- Comparing calculated totals with the published population count.
- Reporting any mismatches without modifying the original data.
- Reviewing affected records before any further decisions are made.

### Why This Matters for Responsible Interpretation

Population measures describe groups of residents rather than individual people. Validating relationships between demographic groups helps ensure that deprivation measures are interpreted in an appropriate context and that neighbourhoods are represented accurately.

By checking population totals before further analysis, this project supports transparency, data integrity, and responsible use of demographic information.

### Ethical Finding

The three non-overlapping age groups were compared with the published total population for each Dudley LSOA. Any discrepancies were identified and reported for review without altering the original dataset. This validation step helps ensure that demographic information remains internally consistent and suitable for responsible analysis.

In [13]:
# Developed with ChatGPT assistance to check population totals.

# Select the three age groups covering the total population.
age_columns = [
    "Dependent Children aged 0-15: mid 2015 (excluding prisoners)",
    "Population aged 16-59: mid 2015 (excluding prisoners)",
    "Older population aged 60 and over: mid 2015 (excluding prisoners)"
]
total_column = "Total population: mid 2015 (excluding prisoners)"

# Compare the age-group sum with the stated total.
age_total = iod_clean[age_columns].sum(axis=1)
population_difference = age_total - iod_clean[total_column]
population_mismatch = population_difference.ne(0)

print(
    "Rows where age groups do not match the total:",
    population_mismatch.sum()
)

# Preview any mismatches, limiting the output to five rows.
display(
    iod_clean.loc[
        population_mismatch,
        ["LSOA code (2011)", total_column] + age_columns
    ].head()
)

Rows where age groups do not match the total: 0

Empty DataFrame
Columns: [LSOA code (2011), Total population: mid 2015 (excluding prisoners), Dependent Children aged 0-15: mid 2015 (excluding prisoners), Population aged 16-59: mid 2015 (excluding prisoners), Older population aged 60 and over: mid 2015 (excluding prisoners)]
Index: []

### Findings
- The three age groups sum exactly to the stated mid-2015 total
  population for all 201 Dudley records.
- No mismatches were found, so the displayed exceptions table is empty.
- The overlapping employment-domain working-age population was
  excluded from this calculation.
- No corrections were required.

---

## 11. Confirm the Source and Record Geographic Limitations

### Source
This dataset is File 7 from the English Indices of Deprivation 2019,
published by the Ministry of Housing, Communities and Local Government.
Its headers and first-row values were matched against the official file.

Source: https://www.gov.uk/government/statistics/english-indices-of-deprivation-2019

The release uses 2011 LSOA geography. Several population denominators
refer to mid-2015; the release year does not mean all underlying
measurements were collected in 2019.

### Decision
Retain this dataset as historical deprivation context alongside
Census 2021 data. It will not be presented as current deprivation
conditions.

### Geographic Coverage
- The deprivation dataset contains 201 Dudley areas.
- The Census datasets contain 203 Dudley areas.
- They share 199 LSOA codes.
- The planned combined analysis will use these matching areas,
  subject to checking boundary compatibility.
- This would exclude two deprivation areas and four Census areas
  from the combined analysis.
- Full cleaned source datasets will be retained.
- The reduced coverage and different source dates will be documented
  when interpreting results.

## Ethical Considerations When Confirming the Source and Geographic Limitations

This step documents the origin, age, and geographic coverage of the IMD dataset before it is combined with Census data. Recording these limitations is an important ethical practice because datasets collected at different times and using different geographic boundaries may not be directly comparable.

### Why Ethical Documentation Matters

The English Indices of Deprivation 2019 are frequently used to understand patterns of disadvantage across neighbourhoods. However, the dataset represents a specific point in time and uses 2011 LSOA geography. Without documenting these limitations, users may incorrectly assume that the deprivation measures describe present-day conditions.

Documenting the source and coverage helps to:

- Improve transparency about where the data originated.
- Clarify the age and context of the information.
- Identify differences between datasets before merging.
- Reduce the risk of misleading comparisons.
- Support responsible interpretation of deprivation measures.

### Ethical Risks if Source Information and Limitations Are Ignored

If source dates and geographic limitations are not clearly documented, several ethical risks may arise:

- **Misrepresentation of current conditions**  
  Historical deprivation measures may be interpreted as reflecting present-day neighbourhood circumstances.

- **Geographic bias**  
  Differences in LSOA coverage may result in some neighbourhoods being excluded from combined analysis.

- **Misleading comparisons**  
  Analyses may compare areas that do not share identical boundaries or time periods.

- **Loss of transparency**  
  Users may not understand why record counts differ between datasets.

### Ethical Safeguards Used in This Step

This review process includes several responsible practices:

- Verifying the dataset against the official government source.
- Documenting the use of 2011 LSOA geography.
- Recognising that some population measures refer to mid-2015 estimates.
- Recording differences in geographic coverage between datasets.
- Retaining all original cleaned datasets for auditing and verification.
- Documenting any areas excluded from combined analysis.

### Why This Matters for Responsible Interpretation

Deprivation indicators provide valuable historical context but should not be interpreted as current measures of neighbourhood conditions without appropriate evidence. Differences in data collection dates and geographic coverage must be considered when comparing deprivation with Census 2021 measures.

By documenting the dataset source, time period, and geographic limitations, this project promotes transparency, reduces the risk of misinterpretation, and supports responsible analysis of deprivation patterns across Dudley.

### Ethical Finding

The IMD dataset was verified against the official government publication and retained as a source of historical deprivation context. Geographic comparison identified coverage differences between the IMD and Census datasets, meaning not all Dudley areas can be included in the combined analysis. These limitations will be documented when interpreting results to ensure findings remain transparent and appropriately qualified.

## 12. Check Remaining Deprivation Scores

Check the score columns not covered by the earlier rate validation
for infinite values, and inspect their minimum and maximum values.

These scores use different scales. Negative values will not be
automatically treated as errors or removed.

In [14]:
# Developed with ChatGPT assistance to inspect remaining scores.
import numpy as np

# Select score columns excluding the four rates already checked.
score_columns = [
    column for column in iod_clean.columns
    if "Score" in column and column not in rate_columns
]

# Inspect ranges and check for infinite values without changing data.
score_checks = pd.DataFrame({
    "Minimum": iod_clean[score_columns].min(),
    "Maximum": iod_clean[score_columns].max(),
    "Infinite_values": np.isinf(iod_clean[score_columns]).sum()
})

print(f"Score columns checked: {len(score_columns)}")
display(score_checks)

Score columns checked: 12

                                            Minimum  Maximum  Infinite_values
Index of Multiple Deprivation (IMD) Score     3.360   63.363                0
Education, Skills and Training Score          1.440   92.175                0
Health Deprivation and Disability Score      -0.927    1.722                0
Crime Score                                  -1.737    1.177                0
Barriers to Housing and Services Score        2.233   35.127                0
Living Environment Score                      2.148   59.607                0
Children and Young People Sub-domain Score   -1.867    1.843                0
Adult Skills Sub-domain Score                 0.176    0.625                0
Geographical Barriers Sub-domain Score       -1.238    1.570                0
Wider Barriers Sub-domain Score              -4.914    0.770                0
Indoors Sub-domain Score                     -1.273    1.825                0
Outdoors Sub-domain Score                    -0.951    0.893                0

### Findings
- The 12 remaining score columns contain no infinite values.
- Minimum and maximum values were recorded for each score.
- Several columns contain negative values. These have been retained;
  a negative score alone does not establish a data error.
- The scores have different ranges and should not be interpreted
  as sharing a common scale.
- No values were changed or removed during this check.

---

## 13. Standardise Column Names

Shorten column names and replace spaces and punctuation with
underscores to make the dataset easier to use.

Retain all 57 columns so feature selection can take place later.
Preserve geographic years and population definitions in the names.
Check that the renamed columns remain unique.

## Ethical Considerations When Standardising Column Names

This step standardises the IMD column names by shortening lengthy titles, replacing spaces and punctuation with underscores, and simplifying repeated terminology. The purpose is to improve readability and consistency while preserving the meaning of the original variables.

### Why Ethical Standardisation Matters

Clear and consistent column names make the dataset easier to understand, analyse, and audit. However, simplifying names must be done carefully so that important context is not lost or altered.

Standardising column names helps to:

- Improve dataset readability.
- Support transparent and reproducible analysis.
- Reduce the risk of manual coding errors.
- Maintain consistency across notebooks and datasets.
- Simplify future visualisations and reporting.

### Ethical Risks if Column Names Are Changed Incorrectly

If variables are renamed without care, several ethical risks may arise:

- **Loss of meaning**  
  Important information about deprivation measures may be removed or obscured.

- **Misinterpretation of variables**  
  Users may misunderstand indicators if names become overly simplified.

- **Reduced transparency**  
  It may become difficult to trace cleaned columns back to their official source definitions.

- **Analysis errors**  
  Duplicate or ambiguous names may lead to incorrect calculations or reporting.

### Ethical Safeguards Used in This Step

This renaming process includes several responsible practices:

- Retaining the core meaning of every variable.
- Preserving geographic references and population definitions.
- Standardising punctuation and spacing consistently.
- Checking for duplicate column names before applying changes.
- Renaming columns only, without modifying any data values.
- Retaining all original variables in the dataset.

### Why This Matters for Responsible Interpretation

The IMD dataset contains multiple deprivation indicators that may be used in later analysis and visualisations. Consistent naming improves usability while preserving transparency about what each variable represents.

By standardising column names carefully, this project supports accurate interpretation, reproducibility, and responsible handling of deprivation data.

### Ethical Finding

All column names were standardised using a consistent naming convention while preserving the meaning of the original variables. Duplicate-name checks confirmed that every column remained uniquely identifiable, and no data values were altered during the process.

In [15]:
# Developed with ChatGPT assistance to standardise column names.
import re

# Shorten repeated explanations while retaining measurement types.
def clean_column_name(column):
    column = column.replace(
        "Index of Multiple Deprivation (IMD)", "IMD"
    )
    column = column.replace(
        "Income Deprivation Affecting Children Index (IDACI)", "IDACI"
    )
    column = column.replace(
        "Income Deprivation Affecting Older People (IDAOPI)", "IDAOPI"
    )
    column = re.sub(r"\s*\(where 1 is most deprived[^)]*\)", "", column)
    return re.sub(r"[^A-Za-z0-9]+", "_", column).strip("_")


# Prepare and check the names before applying them.
renamed_columns = [
    clean_column_name(column) for column in iod_clean.columns
]
assert len(renamed_columns) == len(set(renamed_columns)), (
    "Duplicate column names detected."
)

# Rename columns without changing any data values.
iod_clean.columns = renamed_columns

print(f"Columns retained: {iod_clean.shape[1]}")
print("Duplicate column names:", iod_clean.columns.duplicated().sum())

for column in iod_clean.columns:
    print(column)

Columns retained: 57
Duplicate column names: 0
LSOA_code_2011
LSOA_name_2011
Local_Authority_District_code_2019
Local_Authority_District_name_2019
IMD_Score
IMD_Rank
IMD_Decile
Income_Score_rate
Income_Rank
Income_Decile
Employment_Score_rate
Employment_Rank
Employment_Decile
Education_Skills_and_Training_Score
Education_Skills_and_Training_Rank
Education_Skills_and_Training_Decile
Health_Deprivation_and_Disability_Score
Health_Deprivation_and_Disability_Rank
Health_Deprivation_and_Disability_Decile
Crime_Score
Crime_Rank
Crime_Decile
Barriers_to_Housing_and_Services_Score
Barriers_to_Housing_and_Services_Rank
Barriers_to_Housing_and_Services_Decile
Living_Environment_Score
Living_Environment_Rank
Living_Environment_Decile
IDACI_Score_rate
IDACI_Rank
IDACI_Decile
IDAOPI_Score_rate
IDAOPI_Rank
IDAOPI_Decile
Children_and_Young_People_Sub_domain_Score
Children_and_Young_People_Sub_domain_Rank
Children_and_Young_People_Sub_domain_Decile
Adult_Skills_Sub_domain_Score
Adult_Skills_Sub_domain_Rank
Adult_Skills_Sub_domain_Decile
Geographical_Barriers_Sub_domain_Score
Geographical_Barriers_Sub_domain_Rank
Geographical_Barriers_Sub_domain_Decile
Wider_Barriers_Sub_domain_Score
Wider_Barriers_Sub_domain_Rank
Wider_Barriers_Sub_domain_Decile
Indoors_Sub_domain_Score
Indoors_Sub_domain_Rank
Indoors_Sub_domain_Decile
Outdoors_Sub_domain_Score
Outdoors_Sub_domain_Rank
Outdoors_Sub_domain_Decile
Total_population_mid_2015_excluding_prisoners
Dependent_Children_aged_0_15_mid_2015_excluding_prisoners
Population_aged_16_59_mid_2015_excluding_prisoners
Older_population_aged_60_and_over_mid_2015_excluding_prisoners
Working_age_population_18_59_64_for_use_with_Employment_Deprivation_Domain_excluding_prisoners

### Findings
- All 57 columns were retained and their names standardised.
- No duplicate column names were introduced.
- Repeated ranking explanations were removed from the headers.
- Geographic years and population details remain identifiable.
- Only column names were changed; all 201 records and their
  values remain unchanged.

---

## 14. Save the Cleaned Dataset

Save the validated Dudley deprivation dataset as a CSV without
the dataframe index.

Retain all 201 areas and 57 columns. Geographic exclusions and
feature selection will take place later when preparing the
combined dataset. The original raw CSV remains unchanged.

## Ethical Considerations When Saving the Cleaned Dataset

This step saves the validated Dudley IMD dataset as a separate cleaned CSV file while preserving the original source data unchanged. Saving a cleaned version supports reproducibility, transparency, and consistency throughout the remainder of the project.

### Why Ethical Data Preservation Matters

The cleaning and validation process has confirmed that the dataset is suitable for further analysis. Saving the cleaned dataset creates a reliable working copy that can be used in later notebooks without repeating the cleaning process or risking accidental modification of the raw source file.

Saving the cleaned dataset helps to:

- Preserve the results of data-validation checks.
- Improve reproducibility of the analysis.
- Maintain a clear separation between raw and cleaned data.
- Support transparency and auditing.
- Reduce the risk of accidental changes to the original source file.

### Ethical Risks if Cleaned Data Is Not Preserved Properly

If cleaned datasets are not stored carefully, several ethical risks may arise:

- **Loss of reproducibility**  
  Future users may be unable to recreate the analysis workflow.

- **Confusion between source and processed data**  
  Raw data could be unintentionally altered or overwritten.

- **Reduced transparency**  
  It may become difficult to identify which dataset was used in later analysis.

- **Inconsistent results**  
  Different versions of the dataset may produce conflicting findings.

### Ethical Safeguards Used in This Step

This saving process includes several responsible practices:

- Saving the cleaned dataset as a separate file.
- Retaining all validated Dudley records and variables.
- Excluding the dataframe index to avoid creating artificial identifiers.
- Preserving the original source dataset unchanged.
- Recording dataset dimensions after export.
- Retaining all variables so feature selection can be justified later.

### Why This Matters for Responsible Interpretation

The IMD dataset provides historical deprivation context that will later be combined with Census information. Maintaining a clearly documented and validated cleaned dataset helps ensure that future analysis can be audited, reproduced, and interpreted responsibly.

By saving the cleaned dataset separately from the raw source file, this project supports transparency, data integrity, and responsible data management throughout the analysis process.

### Ethical Finding

The validated Dudley IMD dataset was successfully saved as a separate cleaned CSV file containing 201 records and 57 columns. The original source file remains unchanged, ensuring that both the raw and cleaned versions are available for future verification and auditing.

In [16]:
# Developed with ChatGPT assistance to save the cleaned dataset.

# Save all cleaned Dudley records without an extra index column.
output_path = "cleaned_datasets/dudley_iod_cleaned.csv"
iod_clean.to_csv(output_path, index=False)

# Confirm the saved dataset dimensions.
print(f"Saved: {output_path}")
print(f"Rows: {iod_clean.shape[0]}")
print(f"Columns: {iod_clean.shape[1]}")

Saved: cleaned_datasets/dudley_iod_cleaned.csv
Rows: 201
Columns: 57

### Findings
- The cleaned dataset was saved successfully to
  `cleaned_datasets/dudley_iod_cleaned.csv`.
- The file contains 201 Dudley records and 57 columns.
- No dataframe index was exported.
- The original raw CSV remains unchanged.

## Conclusion

The Dudley subset of the English Indices of Deprivation 2019
has been cleaned and saved. Checks found no missing values,
duplicate records or duplicate LSOA codes. Ranks, deciles and
explicit rates passed their range checks. Population counts
were non-negative integers, and the three age groups matched
the total population for every area.

The remaining score columns contained no infinite values.
Negative scores were retained, and column names were standardised
without changing data values.

This dataset provides historical deprivation context. It uses
2011 LSOA geography and shares 199 codes with the Census datasets.
Boundary compatibility must be checked before the planned merge
using those matching areas. The full cleaned dataset retains
all 201 Dudley records.

Area-level deprivation does not establish individual circumstances
or prove causes of unemployment.